var typingTimer;
var doneTypingInterval = 100;

var cityStateMap = {
    "": "",
    "alipur": "Andaman & Nicobar",
    "andaman island": "Andaman & Nicobar",
    "anderson island": "Andaman & Nicobar",
    "arainj-laka-punga": "Andaman & Nicobar",
    "austinabad": "Andaman & Nicobar",
    "bamboo flat": "Andaman & Nicobar",
    "barren island": "Andaman & Nicobar",
    "beadonabad": "Andaman & Nicobar",
    "betapur": "Andaman & Nicobar",
    "bindraban": "Andaman & Nicobar",
    "bonington": "Andaman & Nicobar",
    "brookesabad": "Andaman & Nicobar",
    "cadell point": "Andaman & Nicobar",
    "calicut": "Kerala",
    "chetamale": "Andaman & Nicobar",
    "cinque islands": "Andaman & Nicobar",
    "defence island": "Andaman & Nicobar",
    "digilpur": "Andaman & Nicobar",
    "dolyganj": "Andaman & Nicobar",
    "flat island": "Andaman & Nicobar",
    "geinyale": "Andaman & Nicobar",
    "great coco island": "Andaman & Nicobar",
    "haddo": "Andaman & Nicobar",
    "havelock island": "Andaman & Nicobar",
    "henry lawrence island": "Andaman & Nicobar",
    "herbertabad": "Andaman & Nicobar",
    "hobdaypur": "Andaman & Nicobar",
    "ilichar": "Andaman & Nicobar",
    "ingoie": "Andaman & Nicobar",
    "inteview island": "Andaman & Nicobar",
    "jangli ghat": "Andaman & Nicobar",
    "jhon lawrence island": "Andaman & Nicobar",
    "karen": "Andaman & Nicobar",
    "kartara": "Andaman & Nicobar",
    "kyd islannd": "Andaman & Nicobar",
    "landfall island": "Andaman & Nicobar",
    "little andmand": "Andaman & Nicobar",
    "little coco island": "Andaman & Nicobar",
    "long island": "Andaman & Nicobar",
    "maimyo": "Andaman & Nicobar",
    "malappuram": "Kerala",
    "manglutan": "Andaman & Nicobar",
    "manpur": "Madhya Pradesh",
    "mitha khari": "Andaman & Nicobar",
    "neill island": "Andaman & Nicobar",
    "nicobar island": "Andaman & Nicobar",
    "north brother island": "Andaman & Nicobar",
    "north passage island": "Andaman & Nicobar",
    "north sentinel island": "Andaman & Nicobar",
    "nothen reef island": "Andaman & Nicobar",
    "outram island": "Andaman & Nicobar",
    "pahlagaon": "Andaman & Nicobar",
    "palalankwe": "Andaman & Nicobar",
    "passage island": "Andaman & Nicobar",
    "phaiapong": "Andaman & Nicobar",
    "phoenix island": "Andaman & Nicobar",
    "port blair": "Andaman & Nicobar",
    "preparis island": "Andaman & Nicobar",
    "protheroepur": "Andaman & Nicobar",
    "rangachang": "Andaman & Nicobar",
    "rongat": "Andaman & Nicobar",
    "rutland island": "Andaman & Nicobar",
    "sabari": "Andaman & Nicobar",
    "saddle peak": "Andaman & Nicobar",
    "shadipur": "Andaman & Nicobar",
    "smith island": "Andaman & Nicobar",
    "sound island": "Andaman & Nicobar",
    "south sentinel island": "Andaman & Nicobar",
    "spike island": "Andaman & Nicobar",
    "tarmugli island": "Andaman & Nicobar",
    "taylerabad": "Andaman & Nicobar",
    "titaije": "Andaman & Nicobar",
    "toibalawe": "Andaman & Nicobar",
    "tusonabad": "Andaman & Nicobar",
    "west island": "Andaman & Nicobar",
    "wimberleyganj": "Andaman & Nicobar",
    "yadita": "Andaman & Nicobar",
    "achampet": "Andhra Pradesh",
    "adilabad": "Andhra Pradesh",
    "adoni": "Andhra Pradesh",
    "alampur": "Andhra Pradesh",
    "allagadda": "Andhra Pradesh",
    "alur": "Karnataka",
    "amalapuram": "Andhra Pradesh",
    "amangallu": "Andhra Pradesh",
    "anakapalle": "Andhra Pradesh",
    "anantapur": "Andhra Pradesh",
    "andole": "Andhra Pradesh",
    "araku": "Andhra Pradesh",
    "armoor": "Andhra Pradesh",
    "asifabad": "Andhra Pradesh",
    "aswaraopet": "Andhra Pradesh",
    "atmakur": "Andhra Pradesh",
    "b. kothakota": "Andhra Pradesh",
    "badvel": "Andhra Pradesh",
    "banaganapalle": "Andhra Pradesh",
    "bandar": "Andhra Pradesh",
    "bangarupalem": "Andhra Pradesh",
    "banswada": "Andhra Pradesh",
    "bapatla": "Andhra Pradesh",
    "bellampalli": "Andhra Pradesh",
    "bhadrachalam": "Andhra Pradesh",
    "bhainsa": "Andhra Pradesh",
    "bheemunipatnam": "Andhra Pradesh",
    "bhimadole": "Andhra Pradesh",
    "bhimavaram": "Andhra Pradesh",
    "bhongir": "Andhra Pradesh",
    "bhooragamphad": "Andhra Pradesh",
    "boath": "Andhra Pradesh",
    "bobbili": "Andhra Pradesh",
    "bodhan": "Andhra Pradesh",
    "chandoor": "Andhra Pradesh",
    "chavitidibbalu": "Andhra Pradesh",
    "chejerla": "Andhra Pradesh",
    "chepurupalli": "Andhra Pradesh",
    "cherial": "Andhra Pradesh",
    "chevella": "Andhra Pradesh",
    "chinnor": "Andhra Pradesh",
    "chintalapudi": "Andhra Pradesh",
    "chintapalle": "Andhra Pradesh",
    "chirala": "Andhra Pradesh",
    "chittoor": "Andhra Pradesh",
    "chodavaram": "Andhra Pradesh",
    "cuddapah": "Andhra Pradesh",
    "cumbum": "Tamil Nadu",
    "darsi": "Andhra Pradesh",
    "devarakonda": "Andhra Pradesh",
    "dharmavaram": "Andhra Pradesh",
    "dichpalli": "Andhra Pradesh",
    "divi": "Andhra Pradesh",
    "donakonda": "Andhra Pradesh",
    "dronachalam": "Andhra Pradesh",
    "east godavari": "Andhra Pradesh",
    "eluru": "Andhra Pradesh",
    "eturnagaram": "Andhra Pradesh",
    "gadwal": "Andhra Pradesh",
    "gajapathinagaram": "Andhra Pradesh",
    "gajwel": "Andhra Pradesh",
    "garladinne": "Andhra Pradesh",
    "giddalur": "Andhra Pradesh",
    "godavari": "Andhra Pradesh",
    "gooty": "Andhra Pradesh",
    "gudivada": "Andhra Pradesh",
    "gudur": "Andhra Pradesh",
    "guntur": "Andhra Pradesh",
    "hindupur": "Andhra Pradesh",
    "hunsabad": "Andhra Pradesh",
    "huzurabad": "Andhra Pradesh",
    "huzurnagar": "Andhra Pradesh",
    "hyderabad": "Andhra Pradesh",
    "ibrahimpatnam": "Andhra Pradesh",
    "jaggayyapet": "Andhra Pradesh",
    "jagtial": "Andhra Pradesh",
    "jammalamadugu": "Andhra Pradesh",
    "jangaon": "Andhra Pradesh",
    "jangareddygudem": "Andhra Pradesh",
    "jannaram": "Andhra Pradesh",
    "kadiri": "Andhra Pradesh",
    "kaikaluru": "Andhra Pradesh",
    "kakinada": "Andhra Pradesh",
    "kalwakurthy": "Andhra Pradesh",
    "kalyandurg": "Andhra Pradesh",
    "kamalapuram": "Andhra Pradesh",
    "kamareddy": "Andhra Pradesh",
    "kambadur": "Andhra Pradesh",
    "kanaganapalle": "Andhra Pradesh",
    "kandukuru": "Andhra Pradesh",
    "kanigiri": "Andhra Pradesh",
    "karimnagar": "Andhra Pradesh",
    "kavali": "Andhra Pradesh",
    "khammam": "Andhra Pradesh",
    "khanapur (ap)": "Andhra Pradesh",
    "kodangal": "Andhra Pradesh",
    "koduru": "Andhra Pradesh",
    "koilkuntla": "Andhra Pradesh",
    "kollapur": "Andhra Pradesh",
    "kothagudem": "Andhra Pradesh",
    "kovvur": "Andhra Pradesh",
    "krishna": "Andhra Pradesh",
    "krosuru": "Andhra Pradesh",
    "kuppam": "Andhra Pradesh",
    "kurnool": "Andhra Pradesh",
    "lakkireddipalli": "Andhra Pradesh",
    "madakasira": "Andhra Pradesh",
    "madanapalli": "Andhra Pradesh",
    "madhira": "Andhra Pradesh",
    "madnur": "Andhra Pradesh",
    "mahabubabad": "Andhra Pradesh",
    "mahabubnagar": "Andhra Pradesh",
    "mahadevapur": "Andhra Pradesh",
    "makthal": "Andhra Pradesh",
    "mancherial": "Andhra Pradesh",
    "mandapeta": "Andhra Pradesh",
    "mangalagiri": "Andhra Pradesh",
    "manthani": "Andhra Pradesh",
    "markapur": "Andhra Pradesh",
    "marturu": "Andhra Pradesh",
    "medachal": "Andhra Pradesh",
    "medak": "Andhra Pradesh",
    "medarmetla": "Andhra Pradesh",
    "metpalli": "Andhra Pradesh",
    "mriyalguda": "Andhra Pradesh",
    "mulug": "Andhra Pradesh",
    "mylavaram": "Andhra Pradesh",
    "nagarkurnool": "Andhra Pradesh",
    "nalgonda": "Andhra Pradesh",
    "nallacheruvu": "Andhra Pradesh",
    "nampalle": "Andhra Pradesh",
    "nandigama": "Andhra Pradesh",
    "nandikotkur": "Andhra Pradesh",
    "nandyal": "Andhra Pradesh",
    "narasampet": "Andhra Pradesh",
    "narasaraopet": "Andhra Pradesh",
    "narayanakhed": "Andhra Pradesh",
    "narayanpet": "Andhra Pradesh",
    "narsapur": "Andhra Pradesh",
    "narsipatnam": "Andhra Pradesh",
    "nazvidu": "Andhra Pradesh",
    "nelloe": "Andhra Pradesh",
    "nellore": "Andhra Pradesh",
    "nidamanur": "Andhra Pradesh",
    "nirmal": "Andhra Pradesh",
    "nizamabad": "Andhra Pradesh",
    "nuguru": "Andhra Pradesh",
    "ongole": "Andhra Pradesh",
    "outsarangapalle": "Andhra Pradesh",
    "paderu": "Andhra Pradesh",
    "pakala": "Andhra Pradesh",
    "palakonda": "Andhra Pradesh",
    "paland": "Andhra Pradesh",
    "palmaneru": "Andhra Pradesh",
    "pamuru": "Andhra Pradesh",
    "pargi": "Andhra Pradesh",
    "parkal": "Andhra Pradesh",
    "parvathipuram": "Andhra Pradesh",
    "pathapatnam": "Andhra Pradesh",
    "pattikonda": "Andhra Pradesh",
    "peapalle": "Andhra Pradesh",
    "peddapalli": "Andhra Pradesh",
    "peddapuram": "Andhra Pradesh",
    "penukonda": "Andhra Pradesh",
    "piduguralla": "Andhra Pradesh",
    "piler": "Andhra Pradesh",
    "pithapuram": "Andhra Pradesh",
    "podili": "Andhra Pradesh",
    "polavaram": "Andhra Pradesh",
    "prakasam": "Andhra Pradesh",
    "proddatur": "Andhra Pradesh",
    "pulivendla": "Andhra Pradesh",
    "punganur": "Andhra Pradesh",
    "putturu": "Andhra Pradesh",
    "rajahmundri": "Andhra Pradesh",
    "rajampeta": "Andhra Pradesh",
    "ramachandrapuram": "Andhra Pradesh",
    "ramannapet": "Andhra Pradesh",
    "rampachodavaram": "Andhra Pradesh",
    "rangareddy": "Andhra Pradesh",
    "rapur": "Andhra Pradesh",
    "rayachoti": "Andhra Pradesh",
    "rayadurg": "Andhra Pradesh",
    "razole": "Andhra Pradesh",
    "repalle": "Andhra Pradesh",
    "saluru": "Andhra Pradesh",
    "sangareddy": "Andhra Pradesh",
    "sathupalli": "Andhra Pradesh",
    "sattenapalle": "Andhra Pradesh",
    "satyavedu": "Andhra Pradesh",
    "shadnagar": "Andhra Pradesh",
    "siddavattam": "Andhra Pradesh",
    "siddipet": "Andhra Pradesh",
    "sileru": "Andhra Pradesh",
    "sircilla": "Andhra Pradesh",
    "sirpur kagaznagar": "Andhra Pradesh",
    "sodam": "Andhra Pradesh",
    "sompeta": "Andhra Pradesh",
    "srikakulam": "Andhra Pradesh",
    "srikalahasthi": "Andhra Pradesh",
    "srisailam": "Andhra Pradesh",
    "srungavarapukota": "Andhra Pradesh",
    "sudhimalla": "Andhra Pradesh",
    "sullarpet": "Andhra Pradesh",
    "tadepalligudem": "Andhra Pradesh",
    "tadipatri": "Andhra Pradesh",
    "tanduru": "Andhra Pradesh",
    "tanuku": "Andhra Pradesh",
    "tekkali": "Andhra Pradesh",
    "tenali": "Andhra Pradesh",
    "thungaturthy": "Andhra Pradesh",
    "tirivuru": "Andhra Pradesh",
    "tirupathi": "Andhra Pradesh",
    "tuni": "Andhra Pradesh",
    "udaygiri": "Andhra Pradesh",
    "ulvapadu": "Andhra Pradesh",
    "uravakonda": "Andhra Pradesh",
    "utnor": "Andhra Pradesh",
    "v.r. puram": "Andhra Pradesh",
    "vaimpalli": "Andhra Pradesh",
    "vayalpad": "Andhra Pradesh",
    "venkatgiri": "Andhra Pradesh",
    "venkatgirikota": "Andhra Pradesh",
    "vijayawada": "Andhra Pradesh",
    "vikrabad": "Andhra Pradesh",
    "vinjamuru": "Andhra Pradesh",
    "vinukonda": "Andhra Pradesh",
    "visakhapatnam": "Andhra Pradesh",
    "vizayanagaram": "Andhra Pradesh",
    "vizianagaram": "Andhra Pradesh",
    "vuyyuru": "Andhra Pradesh",
    "wanaparthy": "Andhra Pradesh",
    "warangal": "Andhra Pradesh",
    "wardhannapet": "Andhra Pradesh",
    "yelamanchili": "Andhra Pradesh",
    "yelavaram": "Andhra Pradesh",
    "yeleswaram": "Andhra Pradesh",
    "yellandu": "Andhra Pradesh",
    "yellanuru": "Andhra Pradesh",
    "yellareddy": "Andhra Pradesh",
    "yerragondapalem": "Andhra Pradesh",
    "zahirabad": "Andhra Pradesh",
    "along": "Arunachal Pradesh",
    "anini": "Arunachal Pradesh",
    "anjaw": "Arunachal Pradesh",
    "bameng": "Arunachal Pradesh",
    "basar": "Arunachal Pradesh",
    "changlang": "Arunachal Pradesh",
    "chowkhem": "Arunachal Pradesh",
    "daporizo": "Arunachal Pradesh",
    "dibang valley": "Arunachal Pradesh",
    "dirang": "Arunachal Pradesh",
    "hayuliang": "Arunachal Pradesh",
    "huri": "Arunachal Pradesh",
    "itanagar": "Arunachal Pradesh",
    "jairampur": "Arunachal Pradesh",
    "kalaktung": "Arunachal Pradesh",
    "kameng": "Arunachal Pradesh",
    "khonsa": "Arunachal Pradesh",
    "kolaring": "Arunachal Pradesh",
    "kurung kumey": "Arunachal Pradesh",
    "lohit": "Arunachal Pradesh",
    "lower dibang valley": "Arunachal Pradesh",
    "lower subansiri": "Arunachal Pradesh",
    "mariyang": "Arunachal Pradesh",
    "mechuka": "Arunachal Pradesh",
    "miao": "Arunachal Pradesh",
    "nefra": "Arunachal Pradesh",
    "pakkekesang": "Arunachal Pradesh",
    "pangin": "Arunachal Pradesh",
    "papum pare": "Arunachal Pradesh",
    "passighat": "Arunachal Pradesh",
    "roing": "Arunachal Pradesh",
    "sagalee": "Arunachal Pradesh",
    "seppa": "Arunachal Pradesh",
    "siang": "Arunachal Pradesh",
    "tali": "Arunachal Pradesh",
    "taliha": "Arunachal Pradesh",
    "tawang": "Arunachal Pradesh",
    "tezu": "Arunachal Pradesh",
    "tirap": "Arunachal Pradesh",
    "tuting": "Arunachal Pradesh",
    "upper siang": "Arunachal Pradesh",
    "upper subansiri": "Arunachal Pradesh",
    "yiang kiag": "Arunachal Pradesh",
    "abhayapuri": "Assam",
    "baithalangshu": "Assam",
    "barama": "Assam",
    "barpeta road": "Assam",
    "bihupuria": "Assam",
    "bijni": "Assam",
    "bilasipara": "Assam",
    "bokajan": "Assam",
    "bokakhat": "Assam",
    "boko": "Assam",
    "bongaigaon": "Assam",
    "cachar": "Assam",
    "cachar hills": "Assam",
    "darrang": "Assam",
    "dhakuakhana": "Assam",
    "dhemaji": "Assam",
    "dhubri": "Assam",
    "dibrugarh": "Assam",
    "digboi": "Assam",
    "diphu": "Assam",
    "goalpara": "Assam",
    "gohpur": "Assam",
    "golaghat": "Assam",
    "guwahati": "Assam",
    "hailakandi": "Assam",
    "hajo": "Assam",
    "halflong": "Assam",
    "hojai": "Assam",
    "howraghat": "Assam",
    "jorhat": "Assam",
    "kamrup": "Assam",
    "karbi anglong": "Assam",
    "karimganj": "Assam",
    "kokarajhar": "Assam",
    "kokrajhar": "Assam",
    "lakhimpur": "Assam",
    "maibong": "Assam",
    "majuli": "Assam",
    "mangaldoi": "Assam",
    "mariani": "Assam",
    "marigaon": "Assam",
    "moranhat": "Assam",
    "morigaon": "Assam",
    "nagaon": "Assam",
    "nalbari": "Assam",
    "rangapara": "Assam",
    "sadiya": "Assam",
    "sibsagar": "Assam",
    "silchar": "Assam",
    "sivasagar": "Assam",
    "sonitpur": "Assam",
    "tarabarihat": "Assam",
    "tezpur": "Assam",
    "tinsukia": "Assam",
    "udalgiri": "Assam",
    "udalguri": "Assam",
    "udarbondhbarpeta": "Assam",
    "adhaura": "Bihar",
    "amarpur": "Bihar",
    "araria": "Bihar",
    "areraj": "Bihar",
    "arrah": "Bihar",
    "arwal": "Bihar",
    "aurangabad": "Maharashtra",
    "bagaha": "Bihar",
    "banka": "Bihar",
    "banmankhi": "Bihar",
    "barachakia": "Bihar",
    "barauni": "Bihar",
    "barh": "Bihar",
    "barosi": "Bihar",
    "begusarai": "Bihar",
    "benipatti": "Bihar",
    "benipur": "Bihar",
    "bettiah": "Bihar",
    "bhabhua": "Bihar",
    "bhagalpur": "Bihar",
    "bhojpur": "Bihar",
    "bidupur": "Bihar",
    "biharsharif": "Bihar",
    "bikram": "Bihar",
    "bikramganj": "Bihar",
    "birpur": "Bihar",
    "buxar": "Bihar",
    "chakai": "Bihar",
    "champaran": "Bihar",
    "chapara": "Bihar",
    "dalsinghsarai": "Bihar",
    "danapur": "Bihar",
    "darbhanga": "Bihar",
    "daudnagar": "Bihar",
    "dhaka": "Bihar",
    "dhamdaha": "Bihar",
    "dumraon": "Bihar",
    "ekma": "Bihar",
    "forbesganj": "Bihar",
    "gaya": "Bihar",
    "gogri": "Bihar",
    "gopalganj": "Madhya Pradesh",
    "h.kharagpur": "Bihar",
    "hajipur": "Bihar",
    "hathua": "Bihar",
    "hilsa": "Bihar",
    "imamganj": "Bihar",
    "jahanabad": "Bihar",
    "jainagar": "Bihar",
    "jamshedpur": "Jharkhand",
    "jamui": "Bihar",
    "jehanabad": "Bihar",
    "jhajha": "Bihar",
    "jhanjharpur": "Bihar",
    "kahalgaon": "Bihar",
    "kaimur (bhabua)": "Bihar",
    "katihar": "Bihar",
    "katoria": "Bihar",
    "khagaria": "Bihar",
    "kishanganj": "Rajasthan",
    "korha": "Bihar",
    "lakhisarai": "Bihar",
    "madhepura": "Bihar",
    "madhubani": "Bihar",
    "maharajganj": "Uttar Pradesh",
    "mahua": "Bihar",
    "mairwa": "Bihar",
    "mallehpur": "Bihar",
    "masrakh": "Bihar",
    "mohania": "Bihar",
    "monghyr": "Bihar",
    "motihari": "Bihar",
    "motipur": "Bihar",
    "munger": "Bihar",
    "muzaffarpur": "Bihar",
    "nabinagar": "Bihar",
    "nalanda": "Bihar",
    "narkatiaganj": "Bihar",
    "naugachia": "Bihar",
    "nawada": "Bihar",
    "pakribarwan": "Bihar",
    "pakridayal": "Bihar",
    "patna": "Bihar",
    "phulparas": "Bihar",
    "piro": "Bihar",
    "pupri": "Bihar",
    "purena": "Bihar",
    "purnia": "Bihar",
    "rafiganj": "Bihar",
    "rajauli": "Bihar",
    "ramnagar": "Jammu & Kashmir",
    "raniganj": "Bihar",
    "raxaul": "Bihar",
    "rohtas": "Bihar",
    "rosera": "Bihar",
    "s.bakhtiarpur": "Bihar",
    "saharsa": "Bihar",
    "samastipur": "Bihar",
    "saran": "Bihar",
    "sasaram": "Bihar",
    "seikhpura": "Bihar",
    "sheikhpura": "Bihar",
    "sheohar": "Bihar",
    "sherghati": "Bihar",
    "sidhawalia": "Bihar",
    "singhwara": "Bihar",
    "sitamarhi": "Bihar",
    "siwan": "Bihar",
    "sonepur": "Bihar",
    "supaul": "Bihar",
    "thakurganj": "Bihar",
    "triveniganj": "Bihar",
    "udakishanganj": "Bihar",
    "vaishali": "Bihar",
    "wazirganj": "Bihar",
    "chandigarh": "Punjab",
    "mani marja": "Chandigarh",
    "ambikapur": "Chhattisgarh",
    "antagarh": "Chhattisgarh",
    "arang": "Chhattisgarh",
    "bacheli": "Chhattisgarh",
    "bagbahera": "Chhattisgarh",
    "bagicha": "Chhattisgarh",
    "baikunthpur": "Chhattisgarh",
    "balod": "Chhattisgarh",
    "balodabazar": "Chhattisgarh",
    "balrampur": "Uttar Pradesh",
    "barpalli": "Chhattisgarh",
    "basana": "Chhattisgarh",
    "bastanar": "Chhattisgarh",
    "bastar": "Chhattisgarh",
    "bderajpur": "Chhattisgarh",
    "bemetara": "Chhattisgarh",
    "berla": "Chhattisgarh",
    "bhairongarh": "Chhattisgarh",
    "bhanupratappur": "Chhattisgarh",
    "bharathpur": "Chhattisgarh",
    "bhatapara": "Chhattisgarh",
    "bhilai": "Chhattisgarh",
    "bhilaigarh": "Chhattisgarh",
    "bhopalpatnam": "Chhattisgarh",
    "bijapur": "Karnataka",
    "bilaspur": "Himachal Pradesh",
    "bodla": "Chhattisgarh",
    "bokaband": "Chhattisgarh",
    "chandipara": "Chhattisgarh",
    "chhinagarh": "Chhattisgarh",
    "chhuriakala": "Chhattisgarh",
    "chingmut": "Chhattisgarh",
    "chuikhadan": "Chhattisgarh",
    "dabhara": "Chhattisgarh",
    "dallirajhara": "Chhattisgarh",
    "dantewada": "Chhattisgarh",
    "deobhog": "Chhattisgarh",
    "dhamda": "Chhattisgarh",
    "dhamtari": "Chhattisgarh",
    "dharamjaigarh": "Chhattisgarh",
    "dongargarh": "Chhattisgarh",
    "durg": "Chhattisgarh",
    "durgakondal": "Chhattisgarh",
    "fingeshwar": "Chhattisgarh",
    "gariaband": "Chhattisgarh",
    "garpa": "Chhattisgarh",
    "gharghoda": "Chhattisgarh",
    "gogunda": "Rajasthan",
    "ilamidi": "Chhattisgarh",
    "jagdalpur": "Madhya Pradesh",
    "janjgir": "Chhattisgarh",
    "janjgir-champa": "Chhattisgarh",
    "jarwa": "Chhattisgarh",
    "jashpur": "Chhattisgarh",
    "jashpurnagar": "Chhattisgarh",
    "kabirdham-kawardha": "Chhattisgarh",
    "kanker": "Chhattisgarh",
    "kasdol": "Chhattisgarh",
    "kathdol": "Chhattisgarh",
    "kathghora": "Chhattisgarh",
    "kawardha": "Chhattisgarh",
    "keskal": "Chhattisgarh",
    "khairgarh": "Chhattisgarh",
    "kondagaon": "Chhattisgarh",
    "konta": "Chhattisgarh",
    "korba": "Chhattisgarh",
    "korea": "Chhattisgarh",
    "kota": "Rajasthan",
    "koyelibeda": "Chhattisgarh",
    "kuakunda": "Chhattisgarh",
    "kunkuri": "Chhattisgarh",
    "kurud": "Chhattisgarh",
    "lohadigundah": "Chhattisgarh",
    "lormi": "Chhattisgarh",
    "luckwada": "Chhattisgarh",
    "mahasamund": "Chhattisgarh",
    "makodi": "Chhattisgarh",
    "manendragarh": "Chhattisgarh",
    "marwahi": "Chhattisgarh",
    "mohla": "Chhattisgarh",
    "mungeli": "Chhattisgarh",
    "nagri": "Chhattisgarh",
    "narainpur": "Chhattisgarh",
    "narayanpur": "Chhattisgarh",
    "neora": "Chhattisgarh",
    "netanar": "Chhattisgarh",
    "odgi": "Chhattisgarh",
    "padamkot": "Chhattisgarh",
    "pakhanjur": "Chhattisgarh",
    "pali": "Rajasthan",
    "pandaria": "Chhattisgarh",
    "pandishankar": "Chhattisgarh",
    "parasgaon": "Chhattisgarh",
    "pasan": "Chhattisgarh",
    "patan": "Maharashtra",
    "pathalgaon": "Chhattisgarh",
    "pendra": "Chhattisgarh",
    "pratappur": "Chhattisgarh",
    "premnagar": "Chhattisgarh",
    "raigarh": "Chhattisgarh",
    "raipur": "Rajasthan",
    "rajnandgaon": "Chhattisgarh",
    "rajpur": "Madhya Pradesh",
    "ramchandrapur": "Chhattisgarh",
    "saraipali": "Chhattisgarh",
    "saranggarh": "Chhattisgarh",
    "sarona": "Chhattisgarh",
    "semaria": "Chhattisgarh",
    "shakti": "Chhattisgarh",
    "sitapur": "Uttar Pradesh",
    "sukma": "Chhattisgarh",
    "surajpur": "Chhattisgarh",
    "surguja": "Chhattisgarh",
    "tapkara": "Chhattisgarh",
    "toynar": "Chhattisgarh",
    "udaipur": "Rajasthan",
    "uproda": "Chhattisgarh",
    "wadrainagar": "Chhattisgarh",
    "amal": "Dadra & Nagar Haveli",
    "amli": "Dadra & Nagar Haveli",
    "bedpa": "Dadra & Nagar Haveli",
    "chikhli": "Dadra & Nagar Haveli",
    "dadra & nagar haveli": "Dadra & Nagar Haveli",
    "dahikhed": "Dadra & Nagar Haveli",
    "dolara": "Dadra & Nagar Haveli",
    "galonda": "Dadra & Nagar Haveli",
    "kanadi": "Dadra & Nagar Haveli",
    "karchond": "Dadra & Nagar Haveli",
    "khadoli": "Dadra & Nagar Haveli",
    "kharadpada": "Dadra & Nagar Haveli",
    "kherabari": "Dadra & Nagar Haveli",
    "kherdi": "Dadra & Nagar Haveli",
    "kothar": "Dadra & Nagar Haveli",
    "luari": "Dadra & Nagar Haveli",
    "mashat": "Dadra & Nagar Haveli",
    "rakholi": "Dadra & Nagar Haveli",
    "rudana": "Dadra & Nagar Haveli",
    "saili": "Dadra & Nagar Haveli",
    "sili": "Dadra & Nagar Haveli",
    "silvassa": "Dadra & Nagar Haveli",
    "sindavni": "Dadra & Nagar Haveli",
    "udva": "Dadra & Nagar Haveli",
    "umbarkoi": "Dadra & Nagar Haveli",
    "vansda": "Dadra & Nagar Haveli",
    "vasona": "Dadra & Nagar Haveli",
    "velugam": "Dadra & Nagar Haveli",
    "brancavare": "Daman & Diu",
    "dagasi": "Daman & Diu",
    "daman": "Daman & Diu",
    "diu": "Daman & Diu",
    "magarvara": "Daman & Diu",
    "nagwa": "Daman & Diu",
    "pariali": "Daman & Diu",
    "passo covo": "Daman & Diu",
    "central delhi": "Delhi",
    "east delhi": "Delhi",
    "new delhi": "Delhi",
    "north delhi": "Delhi",
    "north east delhi": "Delhi",
    "north west delhi": "Delhi",
    "south delhi": "Delhi",
    "south west delhi": "Delhi",
    "west delhi": "Delhi",
    "canacona": "Goa",
    "candolim": "Goa",
    "chinchinim": "Goa",
    "cortalim": "Goa",
    "goa": "Goa",
    "jua": "Goa",
    "madgaon": "Goa",
    "mahem": "Goa",
    "mapuca": "Goa",
    "marmagao": "Goa",
    "panji": "Goa",
    "ponda": "Goa",
    "sanvordem": "Goa",
    "terekhol": "Goa",
    "ahmedabad": "Gujarat",
    "ahwa": "Gujarat",
    "amod": "Gujarat",
    "amreli": "Gujarat",
    "anand": "Gujarat",
    "anjar": "Gujarat",
    "ankaleshwar": "Gujarat",
    "babra": "Gujarat",
    "balasinor": "Gujarat",
    "banaskantha": "Gujarat",
    "bansada": "Gujarat",
    "bardoli": "Gujarat",
    "bareja": "Gujarat",
    "baroda": "Madhya Pradesh",
    "barwala": "Haryana",
    "bayad": "Gujarat",
    "bhachav": "Gujarat",
    "bhanvad": "Gujarat",
    "bharuch": "Gujarat",
    "bhavnagar": "Gujarat",
    "bhiloda": "Gujarat",
    "bhuj": "Gujarat",
    "billimora": "Gujarat",
    "borsad": "Gujarat",
    "botad": "Gujarat",
    "chanasma": "Gujarat",
    "chhota udaipur": "Gujarat",
    "chotila": "Gujarat",
    "dabhoi": "Gujarat",
    "dahod": "Gujarat",
    "damnagar": "Gujarat",
    "dang": "Gujarat",
    "danta": "Gujarat",
    "dasada": "Gujarat",
    "dediapada": "Gujarat",
    "deesa": "Gujarat",
    "dehgam": "Gujarat",
    "deodar": "Gujarat",
    "devgadhbaria": "Gujarat",
    "dhandhuka": "Gujarat",
    "dhanera": "Gujarat",
    "dharampur": "Gujarat",
    "dhari": "Gujarat",
    "dholka": "Gujarat",
    "dhoraji": "Gujarat",
    "dhrangadhra": "Gujarat",
    "dhrol": "Gujarat",
    "dwarka": "Gujarat",
    "fortsongadh": "Gujarat",
    "gadhada": "Gujarat",
    "gandhi nagar": "Gujarat",
    "gariadhar": "Gujarat",
    "godhra": "Gujarat",
    "gogodar": "Gujarat",
    "gondal": "Gujarat",
    "halol": "Gujarat",
    "halvad": "Gujarat",
    "harij": "Gujarat",
    "himatnagar": "Gujarat",
    "idar": "Gujarat",
    "jambusar": "Gujarat",
    "jamjodhpur": "Gujarat",
    "jamkalyanpur": "Gujarat",
    "jamnagar": "Gujarat",
    "jasdan": "Gujarat",
    "jetpur": "Gujarat",
    "jhagadia": "Gujarat",
    "jhalod": "Gujarat",
    "jodia": "Gujarat",
    "junagadh": "Gujarat",
    "junagarh": "Gujarat",
    "kalawad": "Gujarat",
    "kalol": "Gujarat",
    "kapad wanj": "Gujarat",
    "keshod": "Gujarat",
    "khambat": "Gujarat",
    "khambhalia": "Gujarat",
    "khavda": "Gujarat",
    "kheda": "Gujarat",
    "khedbrahma": "Gujarat",
    "kheralu": "Gujarat",
    "kodinar": "Gujarat",
    "kotdasanghani": "Gujarat",
    "kunkawav": "Gujarat",
    "kutch": "Gujarat",
    "kutchmandvi": "Gujarat",
    "kutiyana": "Gujarat",
    "lakhpat": "Gujarat",
    "lakhtar": "Gujarat",
    "lalpur": "Gujarat",
    "limbdi": "Gujarat",
    "limkheda": "Gujarat",
    "lunavada": "Gujarat",
    "m.m.mangrol": "Gujarat",
    "mahuva": "Gujarat",
    "malia-hatina": "Gujarat",
    "maliya": "Gujarat",
    "malpur": "Gujarat",
    "manavadar": "Gujarat",
    "mandvi": "Gujarat",
    "mangrol": "Rajasthan",
    "mehmedabad": "Gujarat",
    "mehsana": "Gujarat",
    "miyagam": "Gujarat",
    "modasa": "Gujarat",
    "morvi": "Gujarat",
    "muli": "Gujarat",
    "mundra": "Gujarat",
    "nadiad": "Gujarat",
    "nakhatrana": "Gujarat",
    "nalia": "Gujarat",
    "narmada": "Gujarat",
    "naswadi": "Gujarat",
    "navasari": "Gujarat",
    "nizar": "Gujarat",
    "okha": "Gujarat",
    "paddhari": "Gujarat",
    "padra": "Gujarat",
    "palanpur": "Gujarat",
    "palitana": "Gujarat",
    "panchmahals": "Gujarat",
    "pavijetpur": "Gujarat",
    "porbandar": "Gujarat",
    "prantij": "Gujarat",
    "radhanpur": "Gujarat",
    "rahpar": "Gujarat",
    "rajaula": "Gujarat",
    "rajkot": "Gujarat",
    "rajpipla": "Gujarat",
    "ranavav": "Gujarat",
    "sabarkantha": "Gujarat",
    "sanand": "Gujarat",
    "sankheda": "Gujarat",
    "santalpur": "Gujarat",
    "santrampur": "Gujarat",
    "savarkundla": "Gujarat",
    "savli": "Gujarat",
    "sayan": "Gujarat",
    "sayla": "Gujarat",
    "shehra": "Gujarat",
    "sidhpur": "Gujarat",
    "sihor": "Gujarat",
    "sojitra": "Gujarat",
    "sumrasar": "Gujarat",
    "surat": "Gujarat",
    "surendranagar": "Gujarat",
    "talaja": "Gujarat",
    "thara": "Gujarat",
    "tharad": "Gujarat",
    "thasra": "Gujarat",
    "una-diu": "Gujarat",
    "upleta": "Gujarat",
    "vadgam": "Gujarat",
    "vadodara": "Gujarat",
    "valia": "Gujarat",
    "vallabhipur": "Gujarat",
    "valod": "Gujarat",
    "valsad": "Gujarat",
    "vanthali": "Gujarat",
    "vapi": "Gujarat",
    "vav": "Gujarat",
    "veraval": "Gujarat",
    "vijapur": "Maharashtra",
    "viramgam": "Gujarat",
    "visavadar": "Gujarat",
    "visnagar": "Gujarat",
    "vyara": "Gujarat",
    "waghodia": "Gujarat",
    "wankaner": "Gujarat",
    "adampur mandi": "Haryana",
    "ambala": "Haryana",
    "assandh": "Haryana",
    "bahadurgarh": "Haryana",
    "barara": "Haryana",
    "bawal": "Haryana",
    "bawanikhera": "Haryana",
    "bhiwani": "Haryana",
    "charkhidadri": "Haryana",
    "cheeka": "Haryana",
    "chhachrauli": "Haryana",
    "dabwali": "Haryana",
    "ellenabad": "Haryana",
    "faridabad": "Haryana",
    "fatehabad": "Haryana",
    "ferojpur jhirka": "Haryana",
    "gharaunda": "Haryana",
    "gohana": "Haryana",
    "gurgaon": "Haryana",
    "hansi": "Haryana",
    "hisar": "Haryana",
    "jagadhari": "Haryana",
    "jatusana": "Haryana",
    "jhajjar": "Haryana",
    "jind": "Haryana",
    "julana": "Haryana",
    "kaithal": "Haryana",
    "kalanaur": "Haryana",
    "kalanwali": "Haryana",
    "kalka": "Haryana",
    "karnal": "Haryana",
    "kosli": "Haryana",
    "kurukshetra": "Haryana",
    "loharu": "Haryana",
    "mahendragarh": "Haryana",
    "meham": "Haryana",
    "mewat": "Haryana",
    "mohindergarh": "Haryana",
    "naraingarh": "Haryana",
    "narnaul": "Haryana",
    "narwana": "Haryana",
    "nilokheri": "Haryana",
    "nuh": "Haryana",
    "palwal": "Haryana",
    "panchkula": "Haryana",
    "panipat": "Haryana",
    "pehowa": "Haryana",
    "ratia": "Haryana",
    "rewari": "Haryana",
    "rohtak": "Haryana",
    "safidon": "Haryana",
    "sirsa": "Haryana",
    "siwani": "Haryana",
    "sonipat": "Haryana",
    "tohana": "Haryana",
    "tohsam": "Haryana",
    "yamunanagar": "Haryana",
    "amb": "Himachal Pradesh",
    "arki": "Himachal Pradesh",
    "banjar": "Himachal Pradesh",
    "bharmour": "Himachal Pradesh",
    "chamba": "Himachal Pradesh",
    "churah": "Himachal Pradesh",
    "dalhousie": "Himachal Pradesh",
    "dehra gopipur": "Himachal Pradesh",
    "hamirpur": "Uttar Pradesh",
    "jogindernagar": "Himachal Pradesh",
    "kalpa": "Himachal Pradesh",
    "kangra": "Himachal Pradesh",
    "kinnaur": "Himachal Pradesh",
    "kullu": "Himachal Pradesh",
    "lahaul": "Himachal Pradesh",
    "mandi": "Himachal Pradesh",
    "nahan": "Himachal Pradesh",
    "nalagarh": "Himachal Pradesh",
    "nirmand": "Himachal Pradesh",
    "nurpur": "Himachal Pradesh",
    "palampur": "Himachal Pradesh",
    "pangi": "Himachal Pradesh",
    "paonta": "Himachal Pradesh",
    "pooh": "Himachal Pradesh",
    "rajgarh": "Uttaranchal",
    "rampur bushahar": "Himachal Pradesh",
    "rohru": "Himachal Pradesh",
    "shimla": "Himachal Pradesh",
    "sirmaur": "Himachal Pradesh",
    "solan": "Himachal Pradesh",
    "spiti": "Himachal Pradesh",
    "sundernagar": "Himachal Pradesh",
    "theog": "Himachal Pradesh",
    "una": "Himachal Pradesh",
    "akhnoor": "Jammu & Kashmir",
    "anantnag": "Jammu & Kashmir",
    "badgam": "Jammu & Kashmir",
    "bandipur": "Jammu & Kashmir",
    "baramulla": "Jammu & Kashmir",
    "basholi": "Jammu & Kashmir",
    "bedarwah": "Jammu & Kashmir",
    "budgam": "Jammu & Kashmir",
    "doda": "Jammu & Kashmir",
    "gulmarg": "Jammu & Kashmir",
    "jammu": "Jammu & Kashmir",
    "kalakot": "Jammu & Kashmir",
    "kargil": "Jammu & Kashmir",
    "karnah": "Jammu & Kashmir",
    "kathua": "Jammu & Kashmir",
    "kishtwar": "Jammu & Kashmir",
    "kulgam": "Jammu & Kashmir",
    "kupwara": "Jammu & Kashmir",
    "leh": "Jammu & Kashmir",
    "mahore": "Jammu & Kashmir",
    "nagrota": "Jammu & Kashmir",
    "nobra": "Jammu & Kashmir",
    "nowshera": "Jammu & Kashmir",
    "nyoma": "Jammu & Kashmir",
    "padam": "Jammu & Kashmir",
    "pahalgam": "Jammu & Kashmir",
    "patnitop": "Jammu & Kashmir",
    "poonch": "Jammu & Kashmir",
    "pulwama": "Jammu & Kashmir",
    "rajouri": "Jammu & Kashmir",
    "ramban": "Jammu & Kashmir",
    "reasi": "Jammu & Kashmir",
    "samba": "Jammu & Kashmir",
    "srinagar": "Jammu & Kashmir",
    "udhampur": "Jammu & Kashmir",
    "vaishno devi": "Jammu & Kashmir",
    "bagodar": "Jharkhand",
    "baharagora": "Jharkhand",
    "balumath": "Jharkhand",
    "barhi": "Jharkhand",
    "barkagaon": "Jharkhand",
    "barwadih": "Jharkhand",
    "basia": "Jharkhand",
    "bermo": "Jharkhand",
    "bhandaria": "Jharkhand",
    "bhawanathpur": "Jharkhand",
    "bishrampur": "Jharkhand",
    "bokaro": "Jharkhand",
    "bolwa": "Jharkhand",
    "bundu": "Jharkhand",
    "chaibasa": "Jharkhand",
    "chainpur": "Jharkhand",
    "chakardharpur": "Jharkhand",
    "chandil": "Jharkhand",
    "chatra": "Jharkhand",
    "chavparan": "Jharkhand",
    "daltonganj": "Jharkhand",
    "deoghar": "Jharkhand",
    "dhanbad": "Jharkhand",
    "dumka": "Jharkhand",
    "dumri": "Jharkhand",
    "garhwa": "Jharkhand",
    "garu": "Jharkhand",
    "ghaghra": "Jharkhand",
    "ghatsila": "Jharkhand",
    "giridih": "Jharkhand",
    "godda": "Jharkhand",
    "gomia": "Jharkhand",
    "govindpur": "Jharkhand",
    "gumla": "Jharkhand",
    "hazaribagh": "Jharkhand",
    "hunterganj": "Jharkhand",
    "ichak": "Jharkhand",
    "itki": "Jharkhand",
    "jagarnathpur": "Jharkhand",
    "jamtara": "Jharkhand",
    "japla": "Jharkhand",
    "jharmundi": "Jharkhand",
    "jhinkpani": "Jharkhand",
    "jhumaritalaiya": "Jharkhand",
    "kathikund": "Jharkhand",
    "kharsawa": "Jharkhand",
    "khunti": "Jharkhand",
    "koderma": "Jharkhand",
    "kolebira": "Jharkhand",
    "latehar": "Jharkhand",
    "lohardaga": "Jharkhand",
    "madhupur": "Jharkhand",
    "mahagama": "Jharkhand",
    "maheshpur raj": "Jharkhand",
    "mandar": "Jharkhand",
    "mandu": "Jharkhand",
    "manoharpur": "Jharkhand",
    "muri": "Jharkhand",
    "nagarutatri": "Jharkhand",
    "nala": "Jharkhand",
    "noamundi": "Jharkhand",
    "pakur": "Jharkhand",
    "palamu": "Jharkhand",
    "palkot": "Jharkhand",
    "rajdhanwar": "Jharkhand",
    "rajmahal": "Jharkhand",
    "ramgarh": "Rajasthan",
    "ranchi": "Jharkhand",
    "sahibganj": "Jharkhand",
    "saraikela": "Jharkhand",
    "simaria": "Jharkhand",
    "simdega": "Jharkhand",
    "singhbhum": "Jharkhand",
    "tisri": "Jharkhand",
    "torpa": "Jharkhand",
    "afzalpur": "Karnataka",
    "ainapur": "Karnataka",
    "aland": "Karnataka",
    "anekal": "Karnataka",
    "ankola": "Karnataka",
    "arsikere": "Karnataka",
    "athani": "Karnataka",
    "aurad": "Karnataka",
    "bableshwar": "Karnataka",
    "badami": "Karnataka",
    "bagalkot": "Karnataka",
    "bagepalli": "Karnataka",
    "bailhongal": "Karnataka",
    "bangalore": "Karnataka",
    "bangalore rural": "Karnataka",
    "bangarpet": "Karnataka",
    "bantwal": "Karnataka",
    "basavakalyan": "Karnataka",
    "basavanabagewadi": "Karnataka",
    "basavapatna": "Karnataka",
    "belgaum": "Karnataka",
    "bellary": "Karnataka",
    "belthangady": "Karnataka",
    "belur": "Karnataka",
    "bhadravati": "Karnataka",
    "bhalki": "Karnataka",
    "bhatkal": "Karnataka",
    "bidar": "Karnataka",
    "biligi": "Karnataka",
    "chadchan": "Karnataka",
    "challakere": "Karnataka",
    "chamrajnagar": "Karnataka",
    "channagiri": "Karnataka",
    "channapatna": "Karnataka",
    "channarayapatna": "Karnataka",
    "chickmagalur": "Karnataka",
    "chikballapur": "Karnataka",
    "chikkaballapur": "Karnataka",
    "chikkanayakanahalli": "Karnataka",
    "chikkodi": "Karnataka",
    "chikmagalur": "Karnataka",
    "chincholi": "Karnataka",
    "chintamani": "Karnataka",
    "chitradurga": "Karnataka",
    "chittapur": "Karnataka",
    "cowdahalli": "Karnataka",
    "davanagere": "Karnataka",
    "deodurga": "Karnataka",
    "devangere": "Karnataka",
    "devarahippargi": "Karnataka",
    "dharwad": "Karnataka",
    "doddaballapur": "Karnataka",
    "gadag": "Karnataka",
    "gangavathi": "Karnataka",
    "gokak": "Karnataka",
    "gowribdanpur": "Karnataka",
    "gubbi": "Karnataka",
    "gulbarga": "Karnataka",
    "gundlupet": "Karnataka",
    "h.b.halli": "Karnataka",
    "h.d. kote": "Karnataka",
    "haliyal": "Karnataka",
    "hampi": "Karnataka",
    "hangal": "Karnataka",
    "harapanahalli": "Karnataka",
    "hassan": "Karnataka",
    "haveri": "Karnataka",
    "hebri": "Karnataka",
    "hirekerur": "Karnataka",
    "hiriyur": "Karnataka",
    "holalkere": "Karnataka",
    "holenarsipur": "Karnataka",
    "honnali": "Karnataka",
    "honnavar": "Karnataka",
    "hosadurga": "Karnataka",
    "hosakote": "Karnataka",
    "hosanagara": "Karnataka",
    "hospet": "Karnataka",
    "hubli": "Karnataka",
    "hukkeri": "Karnataka",
    "humnabad": "Karnataka",
    "hungund": "Karnataka",
    "hunsagi": "Karnataka",
    "hunsur": "Karnataka",
    "huvinahadagali": "Karnataka",
    "indi": "Karnataka",
    "jagalur": "Karnataka",
    "jamkhandi": "Karnataka",
    "jewargi": "Karnataka",
    "joida": "Karnataka",
    "k.r. nagar": "Karnataka",
    "kadur": "Karnataka",
    "kalghatagi": "Karnataka",
    "kamalapur": "Karnataka",
    "kanakapura": "Karnataka",
    "kannada": "Karnataka",
    "kargal": "Karnataka",
    "karkala": "Karnataka",
    "karwar": "Karnataka",
    "khanapur": "Karnataka",
    "kodagu": "Karnataka",
    "kolar": "Karnataka",
    "kollegal": "Karnataka",
    "koppa": "Karnataka",
    "koppal": "Karnataka",
    "koratageri": "Karnataka",
    "krishnarajapet": "Karnataka",
    "kudligi": "Karnataka",
    "kumta": "Karnataka",
    "kundapur": "Karnataka",
    "kundgol": "Karnataka",
    "kunigal": "Karnataka",
    "kurugodu": "Karnataka",
    "kustagi": "Karnataka",
    "lingsugur": "Karnataka",
    "madikeri": "Karnataka",
    "madugiri": "Karnataka",
    "malavalli": "Karnataka",
    "malur": "Karnataka",
    "mandya": "Karnataka",
    "mangalore": "Karnataka",
    "manipal": "Karnataka",
    "manvi": "Karnataka",
    "mashal": "Karnataka",
    "molkalmuru": "Karnataka",
    "mudalgi": "Karnataka",
    "muddebihal": "Karnataka",
    "mudhol": "Karnataka",
    "mudigere": "Karnataka",
    "mulbagal": "Karnataka",
    "mundagod": "Karnataka",
    "mundargi": "Karnataka",
    "murugod": "Karnataka",
    "mysore": "Karnataka",
    "nagamangala": "Karnataka",
    "nanjangud": "Karnataka",
    "nargund": "Karnataka",
    "narsimrajapur": "Karnataka",
    "navalgund": "Karnataka",
    "nelamangala": "Karnataka",
    "nimburga": "Karnataka",
    "pandavapura": "Karnataka",
    "pavagada": "Karnataka",
    "puttur": "Karnataka",
    "raibag": "Karnataka",
    "raichur": "Karnataka",
    "ramdurg": "Karnataka",
    "ranebennur": "Karnataka",
    "ron": "Karnataka",
    "sagar": "Madhya Pradesh",
    "sakleshpur": "Karnataka",
    "salkani": "Karnataka",
    "sandur": "Karnataka",
    "saundatti": "Karnataka",
    "savanur": "Karnataka",
    "sedam": "Karnataka",
    "shahapur": "Maharashtra",
    "shankarnarayana": "Karnataka",
    "shikaripura": "Karnataka",
    "shimoga": "Karnataka",
    "shirahatti": "Karnataka",
    "shorapur": "Karnataka",
    "siddapur": "Karnataka",
    "sidlaghatta": "Karnataka",
    "sindagi": "Karnataka",
    "sindhanur": "Karnataka",
    "sira": "Karnataka",
    "sirsi": "Karnataka",
    "siruguppa": "Karnataka",
    "somwarpet": "Karnataka",
    "sorab": "Karnataka",
    "sringeri": "Karnataka",
    "sriniwaspur": "Karnataka",
    "srirangapatna": "Karnataka",
    "sullia": "Karnataka",
    "t. narsipur": "Karnataka",
    "tallak": "Karnataka",
    "tarikere": "Karnataka",
    "telgi": "Karnataka",
    "thirthahalli": "Karnataka",
    "tiptur": "Karnataka",
    "tumkur": "Karnataka",
    "turuvekere": "Karnataka",
    "udupi": "Karnataka",
    "virajpet": "Karnataka",
    "wadi": "Karnataka",
    "yadgiri": "Karnataka",
    "yelburga": "Karnataka",
    "yellapur": "Karnataka",
    "adimaly": "Kerala",
    "adoor": "Kerala",
    "agathy": "Kerala",
    "alappuzha": "Kerala",
    "alathur": "Kerala",
    "alleppey": "Kerala",
    "alwaye": "Kerala",
    "amini": "Kerala",
    "androth": "Kerala",
    "attingal": "Kerala",
    "badagara": "Kerala",
    "bitra": "Kerala",
    "cannanore": "Kerala",
    "chetlet": "Kerala",
    "ernakulam": "Kerala",
    "idukki": "Kerala",
    "irinjalakuda": "Kerala",
    "kadamath": "Kerala",
    "kalpeni": "Kerala",
    "kalpetta": "Kerala",
    "kanhangad": "Kerala",
    "kanjirapally": "Kerala",
    "kannur": "Kerala",
    "karungapally": "Kerala",
    "kasargode": "Kerala",
    "kavarathy": "Kerala",
    "kiltan": "Kerala",
    "kochi": "Kerala",
    "koduvayur": "Kerala",
    "kollam": "Kerala",
    "kottayam": "Kerala",
    "kovalam": "Kerala",
    "kozhikode": "Kerala",
    "kunnamkulam": "Kerala",
    "mananthodi": "Kerala",
    "manjeri": "Kerala",
    "mannarghat": "Kerala",
    "mavelikkara": "Kerala",
    "minicoy": "Kerala",
    "munnar": "Kerala",
    "muvattupuzha": "Kerala",
    "nedumandad": "Kerala",
    "nedumgandam": "Kerala",
    "nilambur": "Kerala",
    "palai": "Kerala",
    "palakkad": "Kerala",
    "palghat": "Kerala",
    "pathaanamthitta": "Kerala",
    "pathanamthitta": "Kerala",
    "payyanur": "Kerala",
    "peermedu": "Kerala",
    "perinthalmanna": "Kerala",
    "perumbavoor": "Kerala",
    "punalur": "Kerala",
    "quilon": "Kerala",
    "ranni": "Kerala",
    "shertallai": "Kerala",
    "shoranur": "Kerala",
    "taliparamba": "Kerala",
    "tellicherry": "Kerala",
    "thiruvananthapuram": "Kerala",
    "thodupuzha": "Kerala",
    "thrissur": "Kerala",
    "tirur": "Kerala",
    "tiruvalla": "Kerala",
    "trichur": "Kerala",
    "trivandrum": "Kerala",
    "uppala": "Kerala",
    "vadakkanchery": "Kerala",
    "vikom": "Kerala",
    "wayanad": "Kerala",
    "agatti island": "Lakshadweep",
    "bingaram island": "Lakshadweep",
    "bitra island": "Lakshadweep",
    "chetlat island": "Lakshadweep",
    "kadmat island": "Lakshadweep",
    "kalpeni island": "Lakshadweep",
    "kavaratti island": "Lakshadweep",
    "kiltan island": "Lakshadweep",
    "lakshadweep sea": "Lakshadweep",
    "minicoy island": "Lakshadweep",
    "north island": "Lakshadweep",
    "south island": "Lakshadweep",
    "agar": "Madhya Pradesh",
    "ajaigarh": "Madhya Pradesh",
    "alirajpur": "Madhya Pradesh",
    "amarpatan": "Madhya Pradesh",
    "amarwada": "Madhya Pradesh",
    "ambah": "Madhya Pradesh",
    "anuppur": "Madhya Pradesh",
    "arone": "Madhya Pradesh",
    "ashoknagar": "Madhya Pradesh",
    "ashta": "Madhya Pradesh",
    "atner": "Madhya Pradesh",
    "babaichichli": "Madhya Pradesh",
    "badamalhera": "Madhya Pradesh",
    "badarwsas": "Madhya Pradesh",
    "badnagar": "Madhya Pradesh",
    "badnawar": "Madhya Pradesh",
    "badwani": "Madhya Pradesh",
    "bagli": "Madhya Pradesh",
    "baihar": "Madhya Pradesh",
    "balaghat": "Madhya Pradesh",
    "baldeogarh": "Madhya Pradesh",
    "baldi": "Madhya Pradesh",
    "bamori": "Madhya Pradesh",
    "banda": "Uttar Pradesh",
    "bandhavgarh": "Madhya Pradesh",
    "bareli": "Madhya Pradesh",
    "barwaha": "Madhya Pradesh",
    "barwani": "Madhya Pradesh",
    "batkakhapa": "Madhya Pradesh",
    "begamganj": "Madhya Pradesh",
    "beohari": "Madhya Pradesh",
    "berasia": "Madhya Pradesh",
    "berchha": "Madhya Pradesh",
    "betul": "Madhya Pradesh",
    "bhainsdehi": "Madhya Pradesh",
    "bhander": "Madhya Pradesh",
    "bhanpura": "Madhya Pradesh",
    "bhikangaon": "Madhya Pradesh",
    "bhimpur": "Madhya Pradesh",
    "bhind": "Madhya Pradesh",
    "bhitarwar": "Madhya Pradesh",
    "bhopal": "Madhya Pradesh",
    "biaora": "Madhya Pradesh",
    "bijadandi": "Madhya Pradesh",
    "bijawar": "Madhya Pradesh",
    "bijaypur": "Madhya Pradesh",
    "bina": "Madhya Pradesh",
    "birsa": "Madhya Pradesh",
    "birsinghpur": "Madhya Pradesh",
    "budhni": "Madhya Pradesh",
    "burhanpur": "Madhya Pradesh",
    "buxwaha": "Madhya Pradesh",
    "chachaura": "Madhya Pradesh",
    "chanderi": "Madhya Pradesh",
    "chaurai": "Madhya Pradesh",
    "chhapara": "Madhya Pradesh",
    "chhatarpur": "Madhya Pradesh",
    "chhindwara": "Madhya Pradesh",
    "chicholi": "Madhya Pradesh",
    "chitrangi": "Madhya Pradesh",
    "churhat": "Madhya Pradesh",
    "dabra": "Madhya Pradesh",
    "damoh": "Madhya Pradesh",
    "datia": "Madhya Pradesh",
    "deori": "Maharashtra",
    "deosar": "Madhya Pradesh",
    "depalpur": "Madhya Pradesh",
    "dewas": "Madhya Pradesh",
    "dhar": "Madhya Pradesh",
    "dharampuri": "Madhya Pradesh",
    "dindori": "Maharashtra",
    "gadarwara": "Madhya Pradesh",
    "gairatganj": "Madhya Pradesh",
    "ganjbasoda": "Madhya Pradesh",
    "garoth": "Madhya Pradesh",
    "ghansour": "Madhya Pradesh",
    "ghatia": "Madhya Pradesh",
    "ghatigaon": "Madhya Pradesh",
    "ghorandogri": "Madhya Pradesh",
    "ghughari": "Madhya Pradesh",
    "gogaon": "Madhya Pradesh",
    "gohad": "Madhya Pradesh",
    "goharganj": "Madhya Pradesh",
    "gotegaon": "Madhya Pradesh",
    "gourihar": "Madhya Pradesh",
    "guna": "Madhya Pradesh",
    "gunnore": "Madhya Pradesh",
    "gwalior": "Madhya Pradesh",
    "gyraspur": "Madhya Pradesh",
    "hanumana": "Madhya Pradesh",
    "harda": "Madhya Pradesh",
    "harrai": "Madhya Pradesh",
    "harsud": "Madhya Pradesh",
    "hatta": "Madhya Pradesh",
    "hoshangabad": "Madhya Pradesh",
    "ichhawar": "Madhya Pradesh",
    "indore": "Madhya Pradesh",
    "isagarh": "Madhya Pradesh",
    "itarsi": "Madhya Pradesh",
    "jabalpur": "Madhya Pradesh",
    "jabera": "Madhya Pradesh",
    "jaisinghnagar": "Madhya Pradesh",
    "jaithari": "Madhya Pradesh",
    "jaitpur": "Madhya Pradesh",
    "jaitwara": "Madhya Pradesh",
    "jamai": "Madhya Pradesh",
    "jaora": "Madhya Pradesh",
    "jatara": "Madhya Pradesh",
    "jawad": "Madhya Pradesh",
    "jhabua": "Madhya Pradesh",
    "jobat": "Madhya Pradesh",
    "jora": "Madhya Pradesh",
    "kakaiya": "Madhya Pradesh",
    "kannod": "Madhya Pradesh",
    "kannodi": "Madhya Pradesh",
    "karanjia": "Orissa",
    "kareli": "Madhya Pradesh",
    "karera": "Madhya Pradesh",
    "karhal": "Uttar Pradesh",
    "karpa": "Madhya Pradesh",
    "kasrawad": "Madhya Pradesh",
    "katangi": "Madhya Pradesh",
    "katni": "Madhya Pradesh",
    "keolari": "Madhya Pradesh",
    "khachrod": "Madhya Pradesh",
    "khajuraho": "Madhya Pradesh",
    "khakner": "Madhya Pradesh",
    "khalwa": "Madhya Pradesh",
    "khandwa": "Madhya Pradesh",
    "khaniadhana": "Madhya Pradesh",
    "khargone": "Madhya Pradesh",
    "khategaon": "Madhya Pradesh",
    "khetia": "Madhya Pradesh",
    "khilchipur": "Madhya Pradesh",
    "khirkiya": "Madhya Pradesh",
    "khurai": "Madhya Pradesh",
    "kolaras": "Madhya Pradesh",
    "kotma": "Madhya Pradesh",
    "kukshi": "Madhya Pradesh",
    "kundam": "Madhya Pradesh",
    "kurwai": "Madhya Pradesh",
    "kusmi": "Madhya Pradesh",
    "laher": "Madhya Pradesh",
    "lakhnadon": "Madhya Pradesh",
    "lamta": "Madhya Pradesh",
    "lanji": "Madhya Pradesh",
    "lateri": "Madhya Pradesh",
    "laundi": "Madhya Pradesh",
    "maheshwar": "Madhya Pradesh",
    "mahidpurcity": "Madhya Pradesh",
    "maihar": "Madhya Pradesh",
    "majhagwan": "Madhya Pradesh",
    "majholi": "Madhya Pradesh",
    "malhargarh": "Madhya Pradesh",
    "manasa": "Madhya Pradesh",
    "manawar": "Madhya Pradesh",
    "mandla": "Madhya Pradesh",
    "mandsaur": "Madhya Pradesh",
    "mauganj": "Madhya Pradesh",
    "mawai": "Madhya Pradesh",
    "mehgaon": "Madhya Pradesh",
    "mhow": "Madhya Pradesh",
    "morena": "Madhya Pradesh",
    "multai": "Madhya Pradesh",
    "mungaoli": "Madhya Pradesh",
    "nagod": "Madhya Pradesh",
    "nainpur": "Madhya Pradesh",
    "narsingarh": "Madhya Pradesh",
    "narsinghpur": "Orissa",
    "narwar": "Madhya Pradesh",
    "nasrullaganj": "Madhya Pradesh",
    "nateran": "Madhya Pradesh",
    "neemuch": "Madhya Pradesh",
    "niwari": "Madhya Pradesh",
    "niwas": "Madhya Pradesh",
    "nowgaon": "Madhya Pradesh",
    "pachmarhi": "Madhya Pradesh",
    "pandhana": "Madhya Pradesh",
    "pandhurna": "Madhya Pradesh",
    "panna": "Madhya Pradesh",
    "parasia": "Madhya Pradesh",
    "patera": "Madhya Pradesh",
    "patharia": "Madhya Pradesh",
    "pawai": "Madhya Pradesh",
    "petlawad": "Madhya Pradesh",
    "pichhore": "Madhya Pradesh",
    "piparia": "Madhya Pradesh",
    "pohari": "Madhya Pradesh",
    "prabhapattan": "Madhya Pradesh",
    "punasa": "Madhya Pradesh",
    "pushprajgarh": "Madhya Pradesh",
    "raghogarh": "Madhya Pradesh",
    "raghunathpur": "Madhya Pradesh",
    "rahatgarh": "Madhya Pradesh",
    "raisen": "Madhya Pradesh",
    "ratlam": "Madhya Pradesh",
    "rehli": "Madhya Pradesh",
    "rewa": "Madhya Pradesh",
    "sabalgarh": "Madhya Pradesh",
    "sailana": "Madhya Pradesh",
    "sanwer": "Madhya Pradesh",
    "sarangpur": "Madhya Pradesh",
    "sardarpur": "Madhya Pradesh",
    "satna": "Madhya Pradesh",
    "saunsar": "Madhya Pradesh",
    "sehore": "Madhya Pradesh",
    "sendhwa": "Madhya Pradesh",
    "seondha": "Madhya Pradesh",
    "seoni": "Madhya Pradesh",
    "seonimalwa": "Madhya Pradesh",
    "shahdol": "Madhya Pradesh",
    "shahnagar": "Madhya Pradesh",
    "shahpur": "Madhya Pradesh",
    "shajapur": "Madhya Pradesh",
    "sheopur": "Madhya Pradesh",
    "sheopurkalan": "Madhya Pradesh",
    "shivpuri": "Madhya Pradesh",
    "shujalpur": "Madhya Pradesh",
    "sidhi": "Madhya Pradesh",
    "sihora": "Madhya Pradesh",
    "silwani": "Madhya Pradesh",
    "singrauli": "Madhya Pradesh",
    "sirmour": "Madhya Pradesh",
    "sironj": "Madhya Pradesh",
    "sitamau": "Madhya Pradesh",
    "sohagpur": "Madhya Pradesh",
    "sondhwa": "Madhya Pradesh",
    "sonkatch": "Madhya Pradesh",
    "susner": "Madhya Pradesh",
    "tamia": "Madhya Pradesh",
    "tarana": "Madhya Pradesh",
    "tendukheda": "Madhya Pradesh",
    "teonthar": "Madhya Pradesh",
    "thandla": "Madhya Pradesh",
    "tikamgarh": "Madhya Pradesh",
    "timarani": "Madhya Pradesh",
    "udaipura": "Madhya Pradesh",
    "ujjain": "Madhya Pradesh",
    "umaria": "Madhya Pradesh",
    "umariapan": "Madhya Pradesh",
    "vidisha": "Madhya Pradesh",
    "vijayraghogarh": "Madhya Pradesh",
    "waraseoni": "Madhya Pradesh",
    "zhirnia": "Madhya Pradesh",
    "achalpur": "Maharashtra",
    "aheri": "Maharashtra",
    "ahmednagar": "Maharashtra",
    "ahmedpur": "Maharashtra",
    "ajara": "Maharashtra",
    "akkalkot": "Maharashtra",
    "akola": "Maharashtra",
    "akole": "Maharashtra",
    "akot": "Maharashtra",
    "alibagh": "Maharashtra",
    "amagaon": "Maharashtra",
    "amalner": "Maharashtra",
    "ambad": "Maharashtra",
    "ambejogai": "Maharashtra",
    "amravati": "Maharashtra",
    "arjuni merogaon": "Maharashtra",
    "arvi": "Maharashtra",
    "ashti": "Maharashtra",
    "atpadi": "Maharashtra",
    "ausa": "Maharashtra",
    "babhulgaon": "Maharashtra",
    "balapur": "Maharashtra",
    "baramati": "Maharashtra",
    "barshi takli": "Maharashtra",
    "barsi": "Maharashtra",
    "basmatnagar": "Maharashtra",
    "bassein": "Maharashtra",
    "beed": "Maharashtra",
    "bhadrawati": "Maharashtra",
    "bhamregadh": "Maharashtra",
    "bhandara": "Maharashtra",
    "bhir": "Maharashtra",
    "bhiwandi": "Maharashtra",
    "bhiwapur": "Maharashtra",
    "bhokar": "Maharashtra",
    "bhokardan": "Maharashtra",
    "bhoom": "Maharashtra",
    "bhor": "Maharashtra",
    "bhudargad": "Maharashtra",
    "bhusawal": "Maharashtra",
    "billoli": "Maharashtra",
    "brahmapuri": "Maharashtra",
    "buldhana": "Maharashtra",
    "butibori": "Maharashtra",
    "chalisgaon": "Maharashtra",
    "chamorshi": "Maharashtra",
    "chandgad": "Maharashtra",
    "chandrapur": "Maharashtra",
    "chandur": "Maharashtra",
    "chanwad": "Maharashtra",
    "chhikaldara": "Maharashtra",
    "chikhali": "Maharashtra",
    "chinchwad": "Maharashtra",
    "chiplun": "Maharashtra",
    "chopda": "Maharashtra",
    "chumur": "Maharashtra",
    "dahanu": "Maharashtra",
    "dapoli": "Maharashtra",
    "darwaha": "Maharashtra",
    "daryapur": "Maharashtra",
    "daund": "Maharashtra",
    "degloor": "Maharashtra",
    "delhi tanda": "Maharashtra",
    "deogad": "Maharashtra",
    "deolgaonraja": "Maharashtra",
    "desaiganj": "Maharashtra",
    "dhadgaon": "Maharashtra",
    "dhanora": "Maharashtra",
    "dharani": "Maharashtra",
    "dhiwadi": "Maharashtra",
    "dhule": "Maharashtra",
    "dhulia": "Maharashtra",
    "digras": "Maharashtra",
    "edalabad": "Maharashtra",
    "erandul": "Maharashtra",
    "etapalli": "Maharashtra",
    "gadhchiroli": "Maharashtra",
    "gadhinglaj": "Maharashtra",
    "gaganbavada": "Maharashtra",
    "gangakhed": "Maharashtra",
    "gangapur": "Rajasthan",
    "gevrai": "Maharashtra",
    "ghatanji": "Maharashtra",
    "golegaon": "Maharashtra",
    "gondia": "Maharashtra",
    "gondpipri": "Maharashtra",
    "goregaon": "Maharashtra",
    "guhagar": "Maharashtra",
    "hadgaon": "Maharashtra",
    "hatkangale": "Maharashtra",
    "hinganghat": "Maharashtra",
    "hingoli": "Maharashtra",
    "hingua": "Maharashtra",
    "igatpuri": "Maharashtra",
    "indapur": "Maharashtra",
    "islampur": "West Bengal",
    "jalgaon": "Maharashtra",
    "jalna": "Maharashtra",
    "jamkhed": "Maharashtra",
    "jamner": "Maharashtra",
    "jath": "Maharashtra",
    "jawahar": "Maharashtra",
    "jintdor": "Maharashtra",
    "junnar": "Maharashtra",
    "kagal": "Maharashtra",
    "kaij": "Maharashtra",
    "kalamb": "Maharashtra",
    "kalamnuri": "Maharashtra",
    "kallam": "Maharashtra",
    "kalmeshwar": "Maharashtra",
    "kalwan": "Maharashtra",
    "kalyan": "Maharashtra",
    "kamptee": "Maharashtra",
    "kandhar": "Maharashtra",
    "kankavali": "Maharashtra",
    "kannad": "Maharashtra",
    "karad": "Maharashtra",
    "karjat": "Maharashtra",
    "karmala": "Maharashtra",
    "katol": "Maharashtra",
    "kavathemankal": "Maharashtra",
    "kedgaon": "Maharashtra",
    "khadakwasala": "Maharashtra",
    "khamgaon": "Maharashtra",
    "khed": "Maharashtra",
    "khopoli": "Maharashtra",
    "khultabad": "Maharashtra",
    "kinwat": "Maharashtra",
    "kolhapur": "Maharashtra",
    "kopargaon": "Maharashtra",
    "koregaon": "Maharashtra",
    "kudal": "Maharashtra",
    "kuhi": "Maharashtra",
    "kurkheda": "Maharashtra",
    "kusumba": "Maharashtra",
    "lakhandur": "Maharashtra",
    "langa": "Maharashtra",
    "latur": "Maharashtra",
    "lonar": "Maharashtra",
    "lonavala": "Maharashtra",
    "madangad": "Maharashtra",
    "madha": "Maharashtra",
    "mahabaleshwar": "Maharashtra",
    "mahad": "Maharashtra",
    "mahagaon": "Maharashtra",
    "mahasala": "Maharashtra",
    "mahaswad": "Maharashtra",
    "malegaon": "Maharashtra",
    "malgaon": "Maharashtra",
    "malgund": "Maharashtra",
    "malkapur": "Maharashtra",
    "malsuras": "Maharashtra",
    "malwan": "Maharashtra",
    "mancher": "Maharashtra",
    "mangalwedha": "Maharashtra",
    "mangaon": "Maharashtra",
    "mangrulpur": "Maharashtra",
    "manjalegaon": "Maharashtra",
    "manmad": "Maharashtra",
    "maregaon": "Maharashtra",
    "mehda": "Maharashtra",
    "mekhar": "Maharashtra",
    "mohadi": "Maharashtra",
    "mohol": "Maharashtra",
    "mokhada": "Maharashtra",
    "morshi": "Maharashtra",
    "mouda": "Maharashtra",
    "mukhed": "Maharashtra",
    "mul": "Maharashtra",
    "mumbai": "Maharashtra",
    "murbad": "Maharashtra",
    "murtizapur": "Maharashtra",
    "murud": "Maharashtra",
    "nagbhir": "Maharashtra",
    "nagpur": "Maharashtra",
    "nahavara": "Maharashtra",
    "nanded": "Maharashtra",
    "nandgaon": "Maharashtra",
    "nandnva": "Maharashtra",
    "nandurbar": "Maharashtra",
    "narkhed": "Maharashtra",
    "nashik": "Maharashtra",
    "navapur": "Maharashtra",
    "ner": "Maharashtra",
    "newasa": "Maharashtra",
    "nilanga": "Maharashtra",
    "niphad": "Maharashtra",
    "omerga": "Maharashtra",
    "osmanabad": "Maharashtra",
    "pachora": "Maharashtra",
    "paithan": "Maharashtra",
    "palghar": "Maharashtra",
    "pandharkawada": "Maharashtra",
    "pandharpur": "Maharashtra",
    "panhala": "Maharashtra",
    "paranda": "Maharashtra",
    "parbhani": "Maharashtra",
    "parner": "Maharashtra",
    "parola": "Maharashtra",
    "parseoni": "Maharashtra",
    "partur": "Maharashtra",
    "pathardi": "Maharashtra",
    "pathari": "Maharashtra",
    "patoda": "Maharashtra",
    "pauni": "Maharashtra",
    "peint": "Maharashtra",
    "pen": "Maharashtra",
    "phaltan": "Maharashtra",
    "pimpalner": "Maharashtra",
    "pirangut": "Maharashtra",
    "poladpur": "Maharashtra",
    "pune": "Maharashtra",
    "pusad": "Maharashtra",
    "pusegaon": "Maharashtra",
    "radhanagar": "Maharashtra",
    "rahuri": "Maharashtra",
    "raigad": "Maharashtra",
    "rajapur": "Maharashtra",
    "rajgurunagar": "Maharashtra",
    "rajura": "Maharashtra",
    "ralegaon": "Maharashtra",
    "ramtek": "Maharashtra",
    "ratnagiri": "Maharashtra",
    "raver": "Maharashtra",
    "risod": "Maharashtra",
    "roha": "Maharashtra",
    "sakarwadi": "Maharashtra",
    "sakoli": "Maharashtra",
    "sakri": "Maharashtra",
    "salekasa": "Maharashtra",
    "samudrapur": "Maharashtra",
    "sangamner": "Maharashtra",
    "sanganeshwar": "Maharashtra",
    "sangli": "Maharashtra",
    "sangola": "Maharashtra",
    "sanguem": "Maharashtra",
    "saoner": "Maharashtra",
    "saswad": "Maharashtra",
    "satana": "Maharashtra",
    "satara": "Maharashtra",
    "sawantwadi": "Maharashtra",
    "seloo": "Maharashtra",
    "shahada": "Maharashtra",
    "shahuwadi": "Maharashtra",
    "shevgaon": "Maharashtra",
    "shirala": "Maharashtra",
    "shirol": "Maharashtra",
    "shirpur": "Maharashtra",
    "shirur": "Maharashtra",
    "shirwal": "Maharashtra",
    "sholapur": "Maharashtra",
    "shri rampur": "Maharashtra",
    "shrigonda": "Maharashtra",
    "shrivardhan": "Maharashtra",
    "sillod": "Maharashtra",
    "sinderwahi": "Maharashtra",
    "sindhudurg": "Maharashtra",
    "sindkheda": "Maharashtra",
    "sindkhedaraja": "Maharashtra",
    "sinnar": "Maharashtra",
    "sironcha": "Maharashtra",
    "soyegaon": "Maharashtra",
    "surgena": "Maharashtra",
    "talasari": "Maharashtra",
    "talegaon s.ji pant": "Maharashtra",
    "taloda": "Maharashtra",
    "tasgaon": "Maharashtra",
    "thane": "Maharashtra",
    "tirora": "Maharashtra",
    "tiwasa": "Maharashtra",
    "trimbak": "Maharashtra",
    "tuljapur": "Maharashtra",
    "tumsar": "Maharashtra",
    "udgir": "Maharashtra",
    "umarkhed": "Maharashtra",
    "umrane": "Maharashtra",
    "umrer": "Maharashtra",
    "urlikanchan": "Maharashtra",
    "vaduj": "Maharashtra",
    "velhe": "Maharashtra",
    "vengurla": "Maharashtra",
    "vita": "Maharashtra",
    "wada": "Maharashtra",
    "wai": "Maharashtra",
    "walchandnagar": "Maharashtra",
    "wani": "Maharashtra",
    "wardha": "Maharashtra",
    "warlydwarud": "Maharashtra",
    "warora": "Maharashtra",
    "washim": "Maharashtra",
    "wathar": "Maharashtra",
    "yavatmal": "Maharashtra",
    "yawal": "Maharashtra",
    "yeola": "Maharashtra",
    "yeotmal": "Maharashtra",
    "bishnupur": "Manipur",
    "chakpikarong": "Manipur",
    "chandel": "Manipur",
    "chattrik": "Manipur",
    "churachandpur": "Manipur",
    "imphal": "Manipur",
    "jiribam": "Manipur",
    "kakching": "Manipur",
    "kalapahar": "Manipur",
    "mao": "Manipur",
    "mulam": "Manipur",
    "parbung": "Manipur",
    "sadarhills": "Manipur",
    "saibom": "Manipur",
    "sempang": "Manipur",
    "senapati": "Manipur",
    "sochumer": "Manipur",
    "taloulong": "Manipur",
    "tamenglong": "Manipur",
    "thinghat": "Manipur",
    "thoubal": "Manipur",
    "ukhrul": "Manipur",
    "amlaren": "Meghalaya",
    "baghmara": "Meghalaya",
    "cherrapunjee": "Meghalaya",
    "dadengiri": "Meghalaya",
    "garo hills": "Meghalaya",
    "jaintia hills": "Meghalaya",
    "jowai": "Meghalaya",
    "khasi hills": "Meghalaya",
    "khliehriat": "Meghalaya",
    "mariang": "Meghalaya",
    "mawkyrwat": "Meghalaya",
    "nongpoh": "Meghalaya",
    "nongstoin": "Meghalaya",
    "resubelpara": "Meghalaya",
    "ri bhoi": "Meghalaya",
    "shillong": "Meghalaya",
    "tura": "Meghalaya",
    "williamnagar": "Meghalaya",
    "aizawl": "Mizoram",
    "champhai": "Mizoram",
    "demagiri": "Mizoram",
    "kolasib": "Mizoram",
    "lawngtlai": "Mizoram",
    "lunglei": "Mizoram",
    "mamit": "Mizoram",
    "saiha": "Mizoram",
    "serchhip": "Mizoram",
    "dimapur": "Nagaland",
    "jalukie": "Nagaland",
    "kiphire": "Nagaland",
    "kohima": "Nagaland",
    "mokokchung": "Nagaland",
    "mon": "Nagaland",
    "phek": "Nagaland",
    "tuensang": "Nagaland",
    "wokha": "Nagaland",
    "zunheboto": "Nagaland",
    "anandapur": "Orissa",
    "angul": "Orissa",
    "anugul": "Orissa",
    "aska": "Orissa",
    "athgarh": "Orissa",
    "athmallik": "Orissa",
    "attabira": "Orissa",
    "bagdihi": "Orissa",
    "balangir": "Orissa",
    "balasore": "Orissa",
    "baleswar": "Orissa",
    "baliguda": "Orissa",
    "balugaon": "Orissa",
    "banaigarh": "Orissa",
    "bangiriposi": "Orissa",
    "barbil": "Orissa",
    "bargarh": "Orissa",
    "baripada": "Orissa",
    "barkot": "Orissa",
    "basta": "Orissa",
    "berhampur": "West Bengal",
    "betanati": "Orissa",
    "bhadrak": "Orissa",
    "bhanjanagar": "Orissa",
    "bhawanipatna": "Orissa",
    "bhubaneswar": "Orissa",
    "birmaharajpur": "Orissa",
    "bisam cuttack": "Orissa",
    "boriguma": "Orissa",
    "boudh": "Orissa",
    "buguda": "Orissa",
    "chandbali": "Orissa",
    "chhatrapur": "Orissa",
    "chhendipada": "Orissa",
    "cuttack": "Orissa",
    "daringbadi": "Orissa",
    "daspalla": "Orissa",
    "deodgarh": "Orissa",
    "deogarh": "Rajasthan",
    "dhanmandal": "Orissa",
    "dharamgarh": "Orissa",
    "dhenkanal": "Orissa",
    "digapahandi": "Orissa",
    "dunguripali": "Orissa",
    "g. udayagiri": "Orissa",
    "gajapati": "Orissa",
    "ganjam": "Orissa",
    "ghatgaon": "Orissa",
    "gudari": "Orissa",
    "gunupur": "Orissa",
    "hemgiri": "Orissa",
    "hindol": "Orissa",
    "jagatsinghapur": "Orissa",
    "jajpur": "Orissa",
    "jamankira": "Orissa",
    "jashipur": "Orissa",
    "jayapatna": "Orissa",
    "jeypur": "Orissa",
    "jharigan": "Orissa",
    "jharsuguda": "Orissa",
    "jujumura": "Orissa",
    "kalahandi": "Orissa",
    "kalimela": "Orissa",
    "kamakhyanagar": "Orissa",
    "kandhamal": "Orissa",
    "kantabhanji": "Orissa",
    "kantamal": "Orissa",
    "kashipur": "Uttaranchal",
    "kendrapara": "Orissa",
    "kendujhar": "Orissa",
    "keonjhar": "Orissa",
    "khalikote": "Orissa",
    "khordha": "Orissa",
    "khurda": "Orissa",
    "komana": "Orissa",
    "koraput": "Orissa",
    "kotagarh": "Orissa",
    "kuchinda": "Orissa",
    "lahunipara": "Orissa",
    "laxmipur": "Orissa",
    "m. rampur": "Orissa",
    "malkangiri": "Orissa",
    "mathili": "Orissa",
    "mayurbhanj": "Orissa",
    "mohana": "Orissa",
    "motu": "Orissa",
    "nabarangapur": "Orissa",
    "naktideul": "Orissa",
    "nandapur": "Orissa",
    "narlaroad": "Orissa",
    "nayagarh": "West Bengal",
    "nimapara": "Orissa",
    "nowparatan": "Orissa",
    "nowrangapur": "Orissa",
    "nuapada": "Orissa",
    "padampur": "Rajasthan",
    "paikamal": "Orissa",
    "palla hara": "Orissa",
    "papadhandi": "Orissa",
    "parajang": "Orissa",
    "pardip": "Orissa",
    "parlakhemundi": "Orissa",
    "patnagarh": "Orissa",
    "pattamundai": "Orissa",
    "phiringia": "Orissa",
    "phulbani": "Orissa",
    "puri": "Orissa",
    "puruna katak": "Orissa",
    "r. udayigiri": "Orissa",
    "rairakhol": "Orissa",
    "rairangpur": "Orissa",
    "rajgangpur": "Orissa",
    "rajkhariar": "Orissa",
    "rayagada": "Orissa",
    "rourkela": "Orissa",
    "sambalpur": "Orissa",
    "sohela": "Orissa",
    "sonapur": "Orissa",
    "soro": "Orissa",
    "subarnapur": "Orissa",
    "sunabeda": "Orissa",
    "sundergarh": "Orissa",
    "surada": "Orissa",
    "t. rampur": "Orissa",
    "talcher": "Orissa",
    "telkoi": "Orissa",
    "titlagarh": "Orissa",
    "tumudibandha": "Orissa",
    "udala": "Orissa",
    "umerkote": "Orissa",
    "bahur": "Pondicherry",
    "karaikal": "Tamil Nadu",
    "mahe": "Pondicherry",
    "pondicherry": "Tamil Nadu",
    "purnankuppam": "Pondicherry",
    "valudavur": "Pondicherry",
    "villianur": "Pondicherry",
    "yanam": "Pondicherry",
    "abohar": "Punjab",
    "ajnala": "Punjab",
    "amritsar": "Punjab",
    "balachaur": "Punjab",
    "barnala": "Punjab",
    "batala": "Punjab",
    "bathinda": "Punjab",
    "dasua": "Punjab",
    "dinanagar": "Punjab",
    "faridkot": "Punjab",
    "fatehgarh sahib": "Punjab",
    "fazilka": "Punjab",
    "ferozepur": "Punjab",
    "garhashanker": "Punjab",
    "goindwal": "Punjab",
    "gurdaspur": "Punjab",
    "guruharsahai": "Punjab",
    "hoshiarpur": "Punjab",
    "jagraon": "Punjab",
    "jalandhar": "Punjab",
    "jugial": "Punjab",
    "kapurthala": "Punjab",
    "kharar": "Punjab",
    "kotkapura": "Punjab",
    "ludhiana": "Punjab",
    "malaut": "Punjab",
    "malerkotla": "Punjab",
    "mansa": "Punjab",
    "moga": "Punjab",
    "muktasar": "Punjab",
    "nabha": "Punjab",
    "nakodar": "Punjab",
    "nangal": "Punjab",
    "nawanshahar": "Punjab",
    "nawanshahr": "Punjab",
    "pathankot": "Punjab",
    "patiala": "Punjab",
    "patti": "Uttar Pradesh",
    "phagwara": "Punjab",
    "phillaur": "Punjab",
    "phulmandi": "Punjab",
    "quadian": "Punjab",
    "rajpura": "Punjab",
    "raman": "Punjab",
    "rayya": "Punjab",
    "ropar": "Punjab",
    "rupnagar": "Punjab",
    "samana": "Punjab",
    "samrala": "Punjab",
    "sangrur": "Punjab",
    "sardulgarh": "Punjab",
    "sarhind": "Punjab",
    "sas nagar": "Punjab",
    "sultanpur lodhi": "Punjab",
    "sunam": "Punjab",
    "tanda urmar": "Punjab",
    "tarn taran": "Punjab",
    "zira": "Punjab",
    "abu road": "Rajasthan",
    "ahore": "Rajasthan",
    "ajmer": "Rajasthan",
    "aklera": "Rajasthan",
    "alwar": "Rajasthan",
    "amber": "Rajasthan",
    "amet": "Rajasthan",
    "anupgarh": "Rajasthan",
    "asind": "Rajasthan",
    "aspur": "Rajasthan",
    "atru": "Rajasthan",
    "bagidora": "Rajasthan",
    "bali": "Rajasthan",
    "bamanwas": "Rajasthan",
    "banera": "Rajasthan",
    "bansur": "Rajasthan",
    "banswara": "Rajasthan",
    "baran": "Rajasthan",
    "bari": "Rajasthan",
    "barisadri": "Rajasthan",
    "barmer": "Rajasthan",
    "baseri": "Rajasthan",
    "bassi": "Rajasthan",
    "baswa": "Rajasthan",
    "bayana": "Rajasthan",
    "beawar": "Rajasthan",
    "begun": "Rajasthan",
    "behror": "Rajasthan",
    "bhadra": "Rajasthan",
    "bharatpur": "Rajasthan",
    "bhilwara": "Rajasthan",
    "bhim": "Rajasthan",
    "bhinmal": "Rajasthan",
    "bikaner": "Rajasthan",
    "bilara": "Rajasthan",
    "bundi": "Rajasthan",
    "chhabra": "Rajasthan",
    "chhipaborad": "Rajasthan",
    "chirawa": "Rajasthan",
    "chittorgarh": "Rajasthan",
    "chohtan": "Rajasthan",
    "churu": "Rajasthan",
    "dantaramgarh": "Rajasthan",
    "dausa": "Rajasthan",
    "deedwana": "Rajasthan",
    "deeg": "Rajasthan",
    "degana": "Rajasthan",
    "deoli": "Rajasthan",
    "desuri": "Rajasthan",
    "dhariawad": "Rajasthan",
    "dholpur": "Rajasthan",
    "digod": "Rajasthan",
    "dudu": "Rajasthan",
    "dungarpur": "Rajasthan",
    "dungla": "Rajasthan",
    "fatehpur": "Uttar Pradesh",
    "gangdhar": "Rajasthan",
    "gerhi": "Rajasthan",
    "ghatol": "Rajasthan",
    "girwa": "Rajasthan",
    "hanumangarh": "Rajasthan",
    "hindaun": "Rajasthan",
    "hindoli": "Rajasthan",
    "hurda": "Rajasthan",
    "jahazpur": "Rajasthan",
    "jaipur": "Rajasthan",
    "jaisalmer": "Rajasthan",
    "jalore": "Rajasthan",
    "jhalawar": "Rajasthan",
    "jhunjhunu": "Rajasthan",
    "jodhpur": "Rajasthan",
    "kaman": "Rajasthan",
    "kapasan": "Rajasthan",
    "karauli": "Rajasthan",
    "kekri": "Rajasthan",
    "keshoraipatan": "Rajasthan",
    "khandar": "Rajasthan",
    "kherwara": "Rajasthan",
    "khetri": "Rajasthan",
    "kishangarh": "Rajasthan",
    "kishangarhbas": "Rajasthan",
    "kolayat": "Rajasthan",
    "kotputli": "Rajasthan",
    "kotra": "Rajasthan",
    "kotri": "Rajasthan",
    "kumbalgarh": "Rajasthan",
    "kushalgarh": "Rajasthan",
    "ladnun": "Rajasthan",
    "ladpura": "Rajasthan",
    "lalsot": "Rajasthan",
    "laxmangarh": "Rajasthan",
    "lunkaransar": "Rajasthan",
    "mahuwa": "Rajasthan",
    "malpura": "Rajasthan",
    "malvi": "Rajasthan",
    "mandal": "Rajasthan",
    "mandalgarh": "Rajasthan",
    "mandawar": "Rajasthan",
    "marwar-jn": "Rajasthan",
    "merta": "Rajasthan",
    "nadbai": "Rajasthan",
    "nagaur": "Rajasthan",
    "nainwa": "Rajasthan",
    "nasirabad": "Rajasthan",
    "nathdwara": "Rajasthan",
    "nawa": "Rajasthan",
    "neem ka thana": "Rajasthan",
    "newai": "Rajasthan",
    "nimbahera": "Rajasthan",
    "nohar": "Rajasthan",
    "nokha": "Rajasthan",
    "onli": "Rajasthan",
    "osian": "Rajasthan",
    "pachpadara": "Rajasthan",
    "pachpahar": "Rajasthan",
    "parbatsar": "Rajasthan",
    "phagi": "Rajasthan",
    "phalodi": "Rajasthan",
    "pilani": "Rajasthan",
    "pindwara": "Rajasthan",
    "pipalda": "Rajasthan",
    "pirawa": "Rajasthan",
    "pokaran": "Rajasthan",
    "pratapgarh": "Uttar Pradesh",
    "raisinghnagar": "Rajasthan",
    "rajsamand": "Rajasthan",
    "ramganj mandi": "Rajasthan",
    "rashmi": "Rajasthan",
    "ratangarh": "Rajasthan",
    "reodar": "Rajasthan",
    "rupbas": "Rajasthan",
    "sadulshahar": "Rajasthan",
    "sagwara": "Rajasthan",
    "sahabad": "Rajasthan",
    "salumber": "Rajasthan",
    "sanchore": "Rajasthan",
    "sangaria": "Rajasthan",
    "sangod": "Rajasthan",
    "sapotra": "Rajasthan",
    "sarada": "Rajasthan",
    "sardarshahar": "Rajasthan",
    "sarwar": "Rajasthan",
    "sawai madhopur": "Rajasthan",
    "shahapura": "Rajasthan",
    "sheo": "Rajasthan",
    "sheoganj": "Rajasthan",
    "shergarh": "Rajasthan",
    "sikar": "Rajasthan",
    "sirohi": "Rajasthan",
    "siwana": "Rajasthan",
    "sojat": "Rajasthan",
    "sri dungargarh": "Rajasthan",
    "sri ganganagar": "Rajasthan",
    "sri karanpur": "Rajasthan",
    "sri madhopur": "Rajasthan",
    "sujangarh": "Rajasthan",
    "taranagar": "Rajasthan",
    "thanaghazi": "Rajasthan",
    "tibbi": "Rajasthan",
    "tijara": "Rajasthan",
    "todaraisingh": "Rajasthan",
    "tonk": "Rajasthan",
    "udaipurwati": "Rajasthan",
    "uniayara": "Rajasthan",
    "vallabhnagar": "Rajasthan",
    "viratnagar": "Rajasthan",
    "barmiak": "Sikkim",
    "be": "Sikkim",
    "bhurtuk": "Sikkim",
    "chhubakha": "Sikkim",
    "chidam": "Sikkim",
    "chubha": "Sikkim",
    "chumikteng": "Sikkim",
    "dentam": "Sikkim",
    "dikchu": "Sikkim",
    "dzongri": "Sikkim",
    "gangtok": "Sikkim",
    "gauzing": "Sikkim",
    "gyalshing": "Sikkim",
    "hema": "Sikkim",
    "kerung": "Sikkim",
    "lachen": "Sikkim",
    "lachung": "Sikkim",
    "lema": "Sikkim",
    "lingtam": "Sikkim",
    "lungthu": "Sikkim",
    "mangan": "Sikkim",
    "namchi": "Sikkim",
    "namthang": "Sikkim",
    "nanga": "Sikkim",
    "nantang": "Sikkim",
    "naya bazar": "Sikkim",
    "padamachen": "Sikkim",
    "pakhyong": "Sikkim",
    "pemayangtse": "Sikkim",
    "phensang": "Sikkim",
    "rangli": "Sikkim",
    "rinchingpong": "Sikkim",
    "sakyong": "Sikkim",
    "samdong": "Sikkim",
    "singtam": "Sikkim",
    "siniolchu": "Sikkim",
    "sombari": "Sikkim",
    "soreng": "Sikkim",
    "sosing": "Sikkim",
    "tekhug": "Sikkim",
    "temi": "Sikkim",
    "tsetang": "Sikkim",
    "tsomgo": "Sikkim",
    "tumlong": "Sikkim",
    "yangang": "Sikkim",
    "yumtang": "Sikkim",
    "ambasamudram": "Tamil Nadu",
    "anamali": "Tamil Nadu",
    "arakandanallur": "Tamil Nadu",
    "arantangi": "Tamil Nadu",
    "aravakurichi": "Tamil Nadu",
    "ariyalur": "Tamil Nadu",
    "arkonam": "Tamil Nadu",
    "arni": "Tamil Nadu",
    "aruppukottai": "Tamil Nadu",
    "attur": "Tamil Nadu",
    "avanashi": "Tamil Nadu",
    "batlagundu": "Tamil Nadu",
    "bhavani": "Tamil Nadu",
    "chengalpattu": "Tamil Nadu",
    "chengam": "Tamil Nadu",
    "chennai": "Tamil Nadu",
    "chidambaram": "Tamil Nadu",
    "chingleput": "Tamil Nadu",
    "coimbatore": "Tamil Nadu",
    "courtallam": "Tamil Nadu",
    "cuddalore": "Tamil Nadu",
    "denkanikoitah": "Tamil Nadu",
    "devakottai": "Tamil Nadu",
    "dharampuram": "Tamil Nadu",
    "dharmapuri": "Tamil Nadu",
    "dindigul": "Tamil Nadu",
    "erode": "Tamil Nadu",
    "gingee": "Tamil Nadu",
    "gobichettipalayam": "Tamil Nadu",
    "gudalur": "Tamil Nadu",
    "gudiyatham": "Tamil Nadu",
    "harur": "Tamil Nadu",
    "hosur": "Tamil Nadu",
    "jayamkondan": "Tamil Nadu",
    "kallkurichi": "Tamil Nadu",
    "kanchipuram": "Tamil Nadu",
    "kangayam": "Tamil Nadu",
    "kanyakumari": "Tamil Nadu",
    "karaikudi": "Tamil Nadu",
    "karur": "Tamil Nadu",
    "keeranur": "Tamil Nadu",
    "kodaikanal": "Tamil Nadu",
    "kodumudi": "Tamil Nadu",
    "kotagiri": "Tamil Nadu",
    "kovilpatti": "Tamil Nadu",
    "krishnagiri": "Tamil Nadu",
    "kulithalai": "Tamil Nadu",
    "kumbakonam": "Tamil Nadu",
    "kuzhithurai": "Tamil Nadu",
    "madurai": "Tamil Nadu",
    "madurantgam": "Tamil Nadu",
    "manamadurai": "Tamil Nadu",
    "manaparai": "Tamil Nadu",
    "mannargudi": "Tamil Nadu",
    "mayiladuthurai": "Tamil Nadu",
    "mayiladutjurai": "Tamil Nadu",
    "mettupalayam": "Tamil Nadu",
    "metturdam": "Tamil Nadu",
    "mudukulathur": "Tamil Nadu",
    "mulanur": "Tamil Nadu",
    "musiri": "Tamil Nadu",
    "nagapattinam": "Tamil Nadu",
    "nagarcoil": "Tamil Nadu",
    "namakkal": "Tamil Nadu",
    "nanguneri": "Tamil Nadu",
    "natham": "Tamil Nadu",
    "neyveli": "Tamil Nadu",
    "nilgiris": "Tamil Nadu",
    "oddanchatram": "Tamil Nadu",
    "omalpur": "Tamil Nadu",
    "ootacamund": "Tamil Nadu",
    "ooty": "Tamil Nadu",
    "orathanad": "Tamil Nadu",
    "palacode": "Tamil Nadu",
    "palani": "Tamil Nadu",
    "palladum": "Tamil Nadu",
    "papanasam": "Tamil Nadu",
    "paramakudi": "Tamil Nadu",
    "pattukottai": "Tamil Nadu",
    "perambalur": "Tamil Nadu",
    "perundurai": "Tamil Nadu",
    "pollachi": "Tamil Nadu",
    "polur": "Tamil Nadu",
    "ponnamaravathi": "Tamil Nadu",
    "ponneri": "Tamil Nadu",
    "pudukkottai": "Tamil Nadu",
    "rajapalayam": "Tamil Nadu",
    "ramanathapuram": "Tamil Nadu",
    "rameshwaram": "Tamil Nadu",
    "ranipet": "Tamil Nadu",
    "rasipuram": "Tamil Nadu",
    "salem": "Tamil Nadu",
    "sankagiri": "Tamil Nadu",
    "sankaran": "Tamil Nadu",
    "sathiyamangalam": "Tamil Nadu",
    "sivaganga": "Tamil Nadu",
    "sivakasi": "Tamil Nadu",
    "sriperumpudur": "Tamil Nadu",
    "srivaikundam": "Tamil Nadu",
    "tenkasi": "Tamil Nadu",
    "thanjavur": "Tamil Nadu",
    "theni": "Tamil Nadu",
    "thirumanglam": "Tamil Nadu",
    "thiruraipoondi": "Tamil Nadu",
    "thoothukudi": "Tamil Nadu",
    "thuraiyure": "Tamil Nadu",
    "tindivanam": "Tamil Nadu",
    "tiruchendur": "Tamil Nadu",
    "tiruchengode": "Tamil Nadu",
    "tiruchirappalli": "Tamil Nadu",
    "tirunelvelli": "Tamil Nadu",
    "tirupathur": "Tamil Nadu",
    "tirupur": "Tamil Nadu",
    "tiruttani": "Tamil Nadu",
    "tiruvallur": "Tamil Nadu",
    "tiruvannamalai": "Tamil Nadu",
    "tiruvarur": "Tamil Nadu",
    "tiruvellore": "Tamil Nadu",
    "tiruvettipuram": "Tamil Nadu",
    "trichy": "Tamil Nadu",
    "tuticorin": "Tamil Nadu",
    "udumalpet": "Tamil Nadu",
    "ulundurpet": "Tamil Nadu",
    "usiliampatti": "Tamil Nadu",
    "uthangarai": "Tamil Nadu",
    "valapady": "Tamil Nadu",
    "valliyoor": "Tamil Nadu",
    "vaniyambadi": "Tamil Nadu",
    "vedasandur": "Tamil Nadu",
    "vellore": "Tamil Nadu",
    "velur": "Tamil Nadu",
    "vilathikulam": "Tamil Nadu",
    "villupuram": "Tamil Nadu",
    "virudhachalam": "Tamil Nadu",
    "virudhunagar": "Tamil Nadu",
    "wandiwash": "Tamil Nadu",
    "yercaud": "Tamil Nadu",
    "agartala": "Tripura",
    "ambasa": "Tripura",
    "bampurbari": "Tripura",
    "belonia": "Tripura",
    "dhalai": "Tripura",
    "dharam nagar": "Tripura",
    "kailashahar": "Tripura",
    "kamal krishnabari": "Tripura",
    "khopaiyapara": "Tripura",
    "khowai": "Tripura",
    "phuldungsei": "Tripura",
    "radha kishore pur": "Tripura",
    "tripura": "Tripura",
    "achhnera": "Uttar Pradesh",
    "agra": "Uttar Pradesh",
    "akbarpur": "Uttar Pradesh",
    "aliganj": "Uttar Pradesh",
    "aligarh": "Uttar Pradesh",
    "allahabad": "Uttar Pradesh",
    "ambedkar nagar": "Uttar Pradesh",
    "amethi": "Uttar Pradesh",
    "amiliya": "Uttar Pradesh",
    "amroha": "Uttar Pradesh",
    "anola": "Uttar Pradesh",
    "atrauli": "Uttar Pradesh",
    "auraiya": "Uttar Pradesh",
    "azamgarh": "Uttar Pradesh",
    "baberu": "Uttar Pradesh",
    "badaun": "Uttar Pradesh",
    "baghpat": "Uttar Pradesh",
    "bagpat": "Uttar Pradesh",
    "baheri": "Uttar Pradesh",
    "bahraich": "Uttar Pradesh",
    "ballia": "Uttar Pradesh",
    "bansdeeh": "Uttar Pradesh",
    "bansgaon": "Uttar Pradesh",
    "bansi": "Uttar Pradesh",
    "barabanki": "Uttar Pradesh",
    "bareilly": "Uttar Pradesh",
    "basti": "Uttar Pradesh",
    "bhadohi": "Uttar Pradesh",
    "bharthana": "Uttar Pradesh",
    "bharwari": "Uttar Pradesh",
    "bhogaon": "Uttar Pradesh",
    "bhognipur": "Uttar Pradesh",
    "bidhuna": "Uttar Pradesh",
    "bijnore": "Uttar Pradesh",
    "bikapur": "Uttar Pradesh",
    "bilari": "Uttar Pradesh",
    "bilgram": "Uttar Pradesh",
    "bilhaur": "Uttar Pradesh",
    "bindki": "Uttar Pradesh",
    "bisalpur": "Uttar Pradesh",
    "bisauli": "Uttar Pradesh",
    "biswan": "Uttar Pradesh",
    "budaun": "Uttar Pradesh",
    "budhana": "Uttar Pradesh",
    "bulandshahar": "Uttar Pradesh",
    "bulandshahr": "Uttar Pradesh",
    "capianganj": "Uttar Pradesh",
    "chakia": "Uttar Pradesh",
    "chandauli": "Uttar Pradesh",
    "charkhari": "Uttar Pradesh",
    "chhata": "Uttar Pradesh",
    "chhibramau": "Uttar Pradesh",
    "chirgaon": "Uttar Pradesh",
    "chitrakoot": "Uttar Pradesh",
    "chunur": "Uttar Pradesh",
    "dadri": "Uttar Pradesh",
    "dalmau": "Uttar Pradesh",
    "dataganj": "Uttar Pradesh",
    "debai": "Uttar Pradesh",
    "deoband": "Uttar Pradesh",
    "deoria": "Uttar Pradesh",
    "derapur": "Uttar Pradesh",
    "dhampur": "Uttar Pradesh",
    "domariyaganj": "Uttar Pradesh",
    "dudhi": "Uttar Pradesh",
    "etah": "Uttar Pradesh",
    "etawah": "Uttar Pradesh",
    "faizabad": "Uttar Pradesh",
    "farrukhabad": "Uttar Pradesh",
    "firozabad": "Uttar Pradesh",
    "garauth": "Uttar Pradesh",
    "garhmukteshwar": "Uttar Pradesh",
    "gautam buddha nagar": "Uttar Pradesh",
    "ghatampur": "Uttar Pradesh",
    "ghaziabad": "Uttar Pradesh",
    "ghazipur": "Uttar Pradesh",
    "ghosi": "Uttar Pradesh",
    "gonda": "Uttar Pradesh",
    "gorakhpur": "Uttar Pradesh",
    "gunnaur": "Uttar Pradesh",
    "haidergarh": "Uttar Pradesh",
    "hapur": "Uttar Pradesh",
    "hardoi": "Uttar Pradesh",
    "harraiya": "Uttar Pradesh",
    "hasanganj": "Uttar Pradesh",
    "hasanpur": "Uttar Pradesh",
    "hathras": "Uttar Pradesh",
    "jalalabad": "Uttar Pradesh",
    "jalaun": "Uttar Pradesh",
    "jalesar": "Uttar Pradesh",
    "jansath": "Uttar Pradesh",
    "jarar": "Uttar Pradesh",
    "jasrana": "Uttar Pradesh",
    "jaunpur": "Uttar Pradesh",
    "jhansi": "Uttar Pradesh",
    "jyotiba phule nagar": "Uttar Pradesh",
    "kadipur": "Uttar Pradesh",
    "kaimganj": "Uttar Pradesh",
    "kairana": "Uttar Pradesh",
    "kaisarganj": "Uttar Pradesh",
    "kalpi": "Uttar Pradesh",
    "kannauj": "Uttar Pradesh",
    "kanpur": "Uttar Pradesh",
    "karchhana": "Uttar Pradesh",
    "karvi": "Uttar Pradesh",
    "kasganj": "Uttar Pradesh",
    "kaushambi": "Uttar Pradesh",
    "kerakat": "Uttar Pradesh",
    "khaga": "Uttar Pradesh",
    "khair": "Uttar Pradesh",
    "khalilabad": "Uttar Pradesh",
    "kheri": "Uttar Pradesh",
    "konch": "Uttar Pradesh",
    "kumaon": "Uttar Pradesh",
    "kunda": "Uttar Pradesh",
    "kushinagar": "Uttar Pradesh",
    "lalganj": "Uttar Pradesh",
    "lalitpur": "Uttar Pradesh",
    "lucknow": "Uttar Pradesh",
    "machlishahar": "Uttar Pradesh",
    "mahoba": "Uttar Pradesh",
    "mainpuri": "Uttar Pradesh",
    "malihabad": "Uttar Pradesh",
    "mariyahu": "Uttar Pradesh",
    "math": "Uttar Pradesh",
    "mathura": "Uttar Pradesh",
    "mau": "Uttar Pradesh",
    "maudaha": "Uttar Pradesh",
    "maunathbhanjan": "Uttar Pradesh",
    "mauranipur": "Uttar Pradesh",
    "mawana": "Uttar Pradesh",
    "meerut": "Uttar Pradesh",
    "mehraun": "Uttar Pradesh",
    "meja": "Uttar Pradesh",
    "mirzapur": "West Bengal",
    "misrikh": "Uttar Pradesh",
    "modinagar": "Uttar Pradesh",
    "mohamdabad": "Uttar Pradesh",
    "mohamdi": "Uttar Pradesh",
    "moradabad": "Uttar Pradesh",
    "musafirkhana": "Uttar Pradesh",
    "muzaffarnagar": "Uttar Pradesh",
    "nagina": "Uttar Pradesh",
    "najibabad": "Uttar Pradesh",
    "nakur": "Uttar Pradesh",
    "nanpara": "Uttar Pradesh",
    "naraini": "Uttar Pradesh",
    "naugarh": "Uttar Pradesh",
    "nawabganj": "Uttar Pradesh",
    "nighasan": "Uttar Pradesh",
    "noida": "Uttar Pradesh",
    "orai": "Uttar Pradesh",
    "padrauna": "Uttar Pradesh",
    "pahasu": "Uttar Pradesh",
    "pharenda": "Uttar Pradesh",
    "phoolpur": "Uttar Pradesh",
    "phulpur": "Uttar Pradesh",
    "pilibhit": "Uttar Pradesh",
    "pitamberpur": "Uttar Pradesh",
    "powayan": "Uttar Pradesh",
    "puranpur": "Uttar Pradesh",
    "purwa": "Uttar Pradesh",
    "raibareli": "Uttar Pradesh",
    "rampur": "Uttar Pradesh",
    "ramsanehi ghat": "Uttar Pradesh",
    "rasara": "Uttar Pradesh",
    "rath": "Uttar Pradesh",
    "robertsganj": "Uttar Pradesh",
    "sadabad": "Uttar Pradesh",
    "safipur": "Uttar Pradesh",
    "sagri": "Uttar Pradesh",
    "saharanpur": "Uttar Pradesh",
    "sahaswan": "Uttar Pradesh",
    "sahjahanpur": "Uttar Pradesh",
    "saidpur": "Uttar Pradesh",
    "salempur": "Uttar Pradesh",
    "salon": "Uttar Pradesh",
    "sambhal": "Uttar Pradesh",
    "sandila": "Uttar Pradesh",
    "sant kabir nagar": "Uttar Pradesh",
    "sant ravidas nagar": "Uttar Pradesh",
    "sardhana": "Uttar Pradesh",
    "shahabad": "Uttar Pradesh",
    "shahganj": "Uttar Pradesh",
    "shahjahanpur": "Uttar Pradesh",
    "shikohabad": "Uttar Pradesh",
    "shravasti": "Uttar Pradesh",
    "siddharthnagar": "Uttar Pradesh",
    "sidhauli": "Uttar Pradesh",
    "sikandra rao": "Uttar Pradesh",
    "sikandrabad": "Uttar Pradesh",
    "siyana": "Uttar Pradesh",
    "sonbhadra": "Uttar Pradesh",
    "soraon": "Uttar Pradesh",
    "sultanpur": "Uttar Pradesh",
    "tanda": "Uttar Pradesh",
    "tarabganj": "Uttar Pradesh",
    "tilhar": "Uttar Pradesh",
    "unnao": "Uttar Pradesh",
    "utraula": "Uttar Pradesh",
    "varanasi": "Uttar Pradesh",
    "zamania": "Uttar Pradesh",
    "almora": "Uttaranchal",
    "bageshwar": "Uttaranchal",
    "bhatwari": "Uttaranchal",
    "chakrata": "Uttaranchal",
    "chamoli": "Uttaranchal",
    "champawat": "Uttaranchal",
    "dehradun": "Uttaranchal",
    "deoprayag": "Uttaranchal",
    "dharchula": "Uttaranchal",
    "dunda": "Uttaranchal",
    "haldwani": "Uttaranchal",
    "haridwar": "Uttaranchal",
    "joshimath": "Uttaranchal",
    "karan prayag": "Uttaranchal",
    "khatima": "Uttaranchal",
    "kichha": "Uttaranchal",
    "lansdown": "Uttaranchal",
    "munsiari": "Uttaranchal",
    "mussoorie": "Uttaranchal",
    "nainital": "Uttaranchal",
    "pantnagar": "Uttaranchal",
    "partapnagar": "Uttaranchal",
    "pauri garhwal": "Uttaranchal",
    "pithoragarh": "Uttaranchal",
    "purola": "Uttaranchal",
    "ranikhet": "Uttaranchal",
    "roorkee": "Uttaranchal",
    "rudraprayag": "Uttaranchal",
    "tehri garhwal": "Uttaranchal",
    "udham singh nagar": "Uttaranchal",
    "ukhimath": "Uttaranchal",
    "uttarkashi": "Uttaranchal",
    "adra": "West Bengal",
    "alipurduar": "West Bengal",
    "amlagora": "West Bengal",
    "arambagh": "West Bengal",
    "asansol": "West Bengal",
    "balurghat": "West Bengal",
    "bankura": "West Bengal",
    "bardhaman": "West Bengal",
    "basirhat": "West Bengal",
    "bethuadahari": "West Bengal",
    "birbhum": "West Bengal",
    "birpara": "West Bengal",
    "bishanpur": "West Bengal",
    "bolpur": "West Bengal",
    "bongoan": "West Bengal",
    "bulbulchandi": "West Bengal",
    "burdwan": "West Bengal",
    "calcutta": "West Bengal",
    "canning": "West Bengal",
    "champadanga": "West Bengal",
    "contai": "West Bengal",
    "cooch behar": "West Bengal",
    "daimond harbour": "West Bengal",
    "dalkhola": "West Bengal",
    "dantan": "West Bengal",
    "darjeeling": "West Bengal",
    "dhaniakhali": "West Bengal",
    "dhuliyan": "West Bengal",
    "dinajpur": "West Bengal",
    "dinhata": "West Bengal",
    "durgapur": "West Bengal",
    "gangajalghati": "West Bengal",
    "gangarampur": "West Bengal",
    "ghatal": "West Bengal",
    "guskara": "West Bengal",
    "habra": "West Bengal",
    "haldia": "West Bengal",
    "harirampur": "West Bengal",
    "harishchandrapur": "West Bengal",
    "hooghly": "West Bengal",
    "howrah": "West Bengal",
    "jagatballavpur": "West Bengal",
    "jalpaiguri": "West Bengal",
    "jhalda": "West Bengal",
    "jhargram": "West Bengal",
    "kakdwip": "West Bengal",
    "kalchini": "West Bengal",
    "kalimpong": "West Bengal",
    "kalna": "West Bengal",
    "kandi": "West Bengal",
    "karimpur": "West Bengal",
    "katwa": "West Bengal",
    "kharagpur": "West Bengal",
    "khatra": "West Bengal",
    "krishnanagar": "West Bengal",
    "mal bazar": "West Bengal",
    "malda": "West Bengal",
    "manbazar": "West Bengal",
    "mathabhanga": "West Bengal",
    "medinipur": "West Bengal",
    "mekhliganj": "West Bengal",
    "murshidabad": "West Bengal",
    "nadia": "West Bengal",
    "nagarakata": "West Bengal",
    "nalhati": "West Bengal",
    "parganas": "West Bengal",
    "purulia": "West Bengal",
    "raiganj": "West Bengal",
    "rampur hat": "West Bengal",
    "ranaghat": "West Bengal",
    "seharabazar": "West Bengal",
    "siliguri": "West Bengal",
    "suri": "West Bengal",
    "takipur": "West Bengal",
    "tamluk": "West Bengal"
}

var typingTimer; 
var doneTypingInterval = 1000; 
var citiesList = []

async function loadAndExecute(functionName, data) {
    const module = await import('/javascript/server-endpoint.js');
    module[functionName](data);
}

function searchCities() {
    var searchTerm = document.getElementById('from-text').value.toLowerCase();

    if (searchTerm == "") {
        console.log("Empty")
        var parentContainerPlaces = document.getElementById("state-city-inner");
        parentContainerPlaces.innerHTML = '';
        return false
    }

    var filteredCities = [];
    var limit = 9;

    for (var city in cityStateMap) {
        if (city.toLowerCase().includes(searchTerm)) {
            filteredCities.push(city);

            if (filteredCities.length === limit) {
                break;
            }
        }
    }

    clearTimeout(typingTimer);
    typingTimer = setTimeout(function () {
        autoComplete(filteredCities);
    }, doneTypingInterval);
}

function autoComplete(cities) {
    var parentContainerPlaces = document.getElementById("state-city-inner");
    citiesList = []
    parentContainerPlaces.innerHTML = '';

    for (var i = 0; i < cities.length; i++) {
        var newElement = document.createElement('div');
        newElement.className = 'display-state-city-children';
        newElement.textContent = `${cities[i].trim().replace(/\b\w/g, char => char.toUpperCase())}, ${cityStateMap[cities[i].toLowerCase().trim()]}`
        citiesList.push(`${cities[i].trim().replace(/\b\w/g, char => char.toUpperCase())}, ${cityStateMap[cities[i].toLowerCase().trim()]}`)
        parentContainerPlaces.appendChild(newElement);
    }
}

document.getElementById('state-city-inner').addEventListener('click', function (event) {
    if (event.target.classList.contains('display-state-city-children')) {

        var index = Array.from(event.target.parentNode.children).indexOf(event.target);
        document.getElementById("from-text").value = citiesList[index]

        loadAndExecute('saveUserFromPlace', citiesList[index])
        
        document.getElementById("display-state-city-container").style.display = "none";
    }
});